### ISSUE TITLE
[neural_additive_models] Script for drawing input graphs?

### ISSUE THREAD

**Issue by JHLiu7** [google-research/google-research#1009]
Hi, I'm wondering if there's a script following the released code base to plot the feature graphs to interpret model predictions, as shown in the paper and talk. Thanks.

**Comment by jagandecapri** [comment]
Hi @JHLiu7 , did you find the script?

**Comment by JHLiu7** [comment]
I didn't find the official one, but this [repo](https://github.com/AmrMKayid/nam) and this [library](https://interpret.ml/docs/ebm.html) might help

**Comment by jagandecapri** [comment]
Thanks @JHLiu7
