### ISSUE TITLE
[SCANN] Python 3.10 support

### ISSUE THREAD

**Issue by PetrBezousek** [google-research/google-research#1011]
from README:

> ScaNN supports Linux environments running Python versions 3.7-3.9.

After upgrading to Tensorflow 2.8.0 (which supports python 3.10) and scann to 1.2.5, I am able to use scann on python 3.10.
Is the README outdated? :thinking:

**Comment by sammymax** [comment]
Feel free to use ScaNN with Python 3.10 if you find it's stable. I'm surprised you were able to install it though, given ScaNN only has wheels on PyPI for Python 3.7 - 3.9 ([link](https://pypi.org/project/scann/1.2.6/#files)). Official Python 3.10 support will be added in the next release.

**Comment by cjrh** [comment]
There is now a 3.10 wheel for ScaNN 1.2.7 so this issue can be closed: https://pypi.org/project/scann/1.2.7/#files
