### ISSUE TITLE
about coltran 'Producing sample after 0 training steps'

### ISSUE THREAD

**Issue by haiderasad** [google-research/google-research#1030]
hi i have checked everything but it seems my model is not loading the checkpoints correctly 
using the following command

`python custom_colorize.py --config=configs/colorizer.py \ --logdir=coltran_coltran/coltran/colorizer --img_dir=imgstotest --store_dir=results \ --mode=recolorize`

my output
`TX 1650 SUPER, pci bus id: 0000:0a:00.0, compute capability: 7.5
2022-03-12 17:01:42.802178: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-03-12 17:01:43.536067: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8204
WARNING:tensorflow:From /home/haider/Documents/color/lib/python3.8/site-packages/tensorflow/python/training/moving_averages.py:457: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0312 17:01:43.937938 140209677809472 deprecation.py:339] From /home/haider/Documents/color/lib/python3.8/site-packages/tensorflow/python/training/moving_averages.py:457: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
I0312 17:01:44.057944 140209677809472 train_utils.py:91] Built with exponential moving average.
I0312 17:01:44.065676 140209677809472 train_utils.py:185] Restoring from /tmp/svt.
I0312 17:01:44.081349 140209677809472 custom_colorize.py:207] Producing sample after 0 training steps.
I0312 17:01:44.081509 140209677809472 custom_colorize.py:210] 1
I0312 17:02:57.903805 140209677809472 custom_colorize.py:232] ['sdasds.jpg', 'flickr_cat_000004.jpg']
I0312 17:02:57.904262 140209677809472 custom_colorize.py:236] results/stage1/sdasds.jpg
I0312 17:02:57.904421 140209677809472 custom_colorize.py:238] (64, 64, 3)
I0312 17:02:57.912902 140209677809472 custom_colorize.py:236] results/stage1/flickr_cat_000004.jpg
I0312 17:02:57.913127 140209677809472 custom_colorize.py:238] (64, 64, 3)
`

**Comment by haiderasad** [comment]
output images
![flickr_cat_000004](https://user-images.githubusercontent.com/55244143/158017284-f855465d-367a-4776-b759-895cedd58913.jpg)

**Comment by MechCoder** [comment]
This line indicates that you are not loading the correct checkpoint directory.

```
 I0312 17:01:44.065676 140209677809472 train_utils.py:185] Restoring from /tmp/svt
```

Are your flags passed correctly? logdir inside the script should point to coltran_coltran/coltran/colorize

**Comment by haiderasad** [comment]
yes i checked again and again, my pre trained model are inside the main dir "coltran/coltran_coltran/coltran/colorizer" , can you please help to debug what can be the problem,do i need to modify configs/colorizer.py?

**Comment by haiderasad** [comment]
UPDATE: i fixed it by setting the path of checkpoint manually in default field of logdir in custom_colorize.py, somehow it was not picking up the flag in the main command

**Comment by haiderasad** [comment]
hi @MechCoder  can the final output dimension  be changed to 512 or 1024 from 256?
