### ISSUE TITLE
InvalidArgumentError: Data too short when trying to read string in Google kws_streaming

### ISSUE THREAD

**Issue by csetanmayjain** [google-research/google-research#1066]
Hi,
I tried to train a custom model, and the training failed due to `InvalidArgumentError: Data too short when trying to read string
	 [[node data/DecodeWav (defined at google-research/kws_streaming/data/input_data.py:415) ]]`

When I trained a model with less number of training steps like `2,2,2,2`, the training is successful on the dataset, whereas if I increase the training steps to `40000,40000,20000,20000`, the training failed.

My dataset contains wav audio between 1 second to 3 seconds with a 16k sampling rate.

**Comment by rybakov** [comment]
Hi @csetanmayjain, this lib does not support training samples with different audio length: all data should have the same length with defined parameter e.g. "--clip_duration_ms=1000" for audio with 1000ms length.

**Comment by rybakov** [comment]
It will crop it in line [wav_decoder = tf.audio.decode_wav(wav_loader, desired_channels=1, desired_samples=desired_samples))](https://github.com/google-research/google-research/blob/master/kws_streaming/data/input_data.py#L414), where desired_samples is defined by clip_duration_ms.

**Comment by csetanmayjain** [comment]
If I'm not wrong, this one is during the decoding?
I have trained a model, keeping "--clip_duration_ms=1000", with the data having 0.5 seconds to 3seconds of audio.
In this,  whether the model was trained on the entire utterance between the audios of 0.5 to 3 seconds or, it trim the 1000 ms of audio, train on it, and discard the rest of the utterance?

**Comment by rybakov** [comment]
audio will be trimmed by 1000ms in above I pointed you to the line in the code where trimming will happen. [tf.audio.decode_wav](https://www.tensorflow.org/api_docs/python/tf/audio/decode_wav) reads audio and trims/crops it.

**Comment by csetanmayjain** [comment]
got it
Thanks for your time @rybakov
