### ISSUE TITLE
[RegNeRF] Possible incorrect formula in the Arxiv preprint paper

### ISSUE THREAD

**Issue by pomelyu** [google-research/google-research#1076]
Thanks for this wonderful work.

The space annealing formula (13) is different between the google drive and arxiv version.
Google drive:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/2679561/165253821-10104415-a58a-4410-bd16-8840910a929b.png">
arixv
<img width="213" alt="image" src="https://user-images.githubusercontent.com/2679561/165254054-f10c1a47-59c5-4aca-9cd8-9c8bff3a4563.png">
Since `Ps` stands for "start range" and the sampling region should be lied in `[t_near, t_far]`, I think google drive version is correct.

**Comment by m-niemeyer** [comment]
Yes, correct, we updated this in the second paper version but the arxiv version is still the old one. Thanks for the pointer, we will update the arxiv paper soon!
