### ISSUE TITLE
DreamFields: Very long training time

### ISSUE THREAD

**Issue by liuzhengzhe** [google-research/google-research#1077]
I deployed the code following the "Running in a virtual environment" guideline on two different GPU servers, I found it will take very long (100 hours and 200 hours) to train even one model with low resolution. My cuda is 11.1.

![image](https://user-images.githubusercontent.com/8349580/165294767-90619200-4043-4984-9280-ccedc02044ad.png)
![image](https://user-images.githubusercontent.com/8349580/165294792-03cfba85-b476-462f-a21c-d9bccc518ee2.png)
![image](https://user-images.githubusercontent.com/8349580/165294800-2c81dae2-cb9c-4bb0-83e6-f4a2c0c218e9.png)

Thanks very much.

**Comment by voodoohop** [comment]
@liuzhengzhe A few months ago dream fields was running much faster on my GPUs. I couldn't figure out what changed if it was some JAX update or something else. 

On TPUs inferrence and training are normal for me

**Comment by liuzhengzhe** [comment]
Thanks for your reply. Now I used the google-colab, which works fine.

**Comment by HaiyiMei** [comment]
I'm facing the same issue right now. 
I'm using `jax 0.3.13, jaxlib 0.3.10+cuda11.cudnn805, cuda 11.3, cudnn8.4.1`.

**Comment by saisurbehera** [comment]
did anyone fix this yet ?

**Comment by mln-wave** [comment]
Hi @liuzhengzhe 
Do you mean that you were able to run colab notebook provided in [this project page](https://ajayj.com/dreamfields)?
Actually I am facing the below error when running the trainng setp in that notebook.
`UnfilteredStackTrace: TypeError: Can't call __hash__ on modules that hold variables.` 

If you have working colab version, can u share the link here?

Thank you!

**Comment by liuzhengzhe** [comment]
Yes, I use this colab demo version and it works fine.

Zhengzhe

mln-wave ***@***.***> 于2022年10月11日周二 17:45写道：

**Comment by mln-wave** [comment]
Hi @liuzhengzhe 
Thanks for the quick reply!

I think jax or some library version has changed since you last ran. Can you once run it now? Or share your notebook?

[This](https://colab.research.google.com/drive/1Sq_Bua2_O5ThFjr5KiP3WCkELA8larBM#scrollTo=PrCmSqTIAor-) is the notebook with the error I am facing.

**Comment by bluestyle97** [comment]
@mln-wave Hi, I met the same error when using the colab notebook:
`UnfilteredStackTrace: TypeError: Can't call __hash__ on modules that hold variables.`
Have you solved this problem?
