### ISSUE TITLE
No module named tensorflow.google

### ISSUE THREAD

**Issue by huiwenzhang** [google-research/google-research#11]
Hi, what the hell tensorflow.google is?  I checked you official tf API and related topics on websites, but found nothing. My tf version is 1.12.0.
Thanks

**Comment by olganw** [comment]
that's a bug, you can replace with regular tensorflow. someone should have a PR soon to update.

**Comment by dbieber** [comment]
Done https://github.com/google-research/google-research/commit/86101e4bf32a56b3753871e5cb5ec063a5e5987d
