### ISSUE TITLE
Mode switching tokens: UL2 Unifying Language Learning Paradigms

### ISSUE THREAD

**Issue by DanielHesslow** [google-research/google-research#1100]
Hi, I can't seem to find what IDs are associated with each mode switching token in the pretrained models for UL2. I guess we use some of the `<extra_id_xx>` tokens are used for this? 

Thanks

**Comment by DanielHesslow** [comment]
Tried with: `<pad>`, `<extra_id_0>`,  `<extra_id_1>`, `<extra_id_2>`, `<extra_id_97>`, `<extra_id_98>`, `<extra_id_99>`  in the t5 tokenizer but pretty much just getting garbage out so far:

Using a random wiki passage on mushrooms with some masked out words, which works fine with t5.

> A mushroom or toadstool is the fleshy, spore-bearing <extra_id_0> body of a fungus, typically produced <extra_id_1>, on soil, or on its food source.
> 
> The standard for the name "mushroom" is the cultivated white button mushroom, Agaricus bisporus; hence the word "mushroom" is most often applied to those fungi (Basidiomycota, Agaricomycetes) that have a stem (stipe), a cap (pileus), and gills (lamellae, sing. lamella) on the underside of the cap. "Mushroom" also describes a variety of other <extra_id_2> fungi, with or without stems, therefore the term is used to describe the fleshy fruiting bodies of some Ascomycota. These gills produce microscopic spores that help the fungus spread across the ground or its occupant surface.
> 

I'm getting the following output with the different conditioning tokens mentioned above:

```
-------------------------------
<pad><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0>s</s>
-------------------------------
<extra_id_0>;<extra_id_0>sis put<extra_id_0>is<extra_id_0>,<extra_id_0>isis<extra_id_0> être Real cross Signh
-------------------------------
<extra_id_1>s Erasmus or" no  mondiale être.. Erasmus...+1ka’u<extra_id_29>
-------------------------------
<extra_id_2>d<extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0> être" that<extra_id_5><extra_id_27>t être êtres
-------------------------------
<extra_id_97><extra_id_0><extra_id_0><extra_id_0>TM garanteaz studyiestatesiesteiano<unk> mega<unk>i<extra_id_0><extra_id_0>
-------------------------------
<extra_id_98><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0>y<extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0><extra_id_0>
-------------------------------
<extra_id_99> domestic<extra_id_11>,,is cheddar</s>
```



Could of course also be an issue the way I'm running the model. If you could provide some example usage of the model that would be very helpful. 

Ping @vanzytay

**Comment by DanielHesslow** [comment]
I seem to have gotten it working now. Had a bug in my cp conversion.  However, regardless of what token I prefix the input with, it appears to be doing `R` denoising. 
> <pad><extra_id_0> fruiting<extra_id_1> above ground on the ground<extra_id_2> fleshy fruiting bodies of<extra_id_3>

**Comment by felix-schneider** [comment]
I'm new to T5X in general, could you share how you are doing inference at all? Don't you need additional `.gin` files, like the base architecture?

**Comment by DanielHesslow** [comment]
Actually I converted it to HFs T5 implementation instead 😅 , I could maybe upload an unofficial port if it's of interest.

**Comment by chessgecko** [comment]
That'd be awesome! I'd even just take your weight conversion script 😊.

**Comment by vanzytay** [comment]
hey! the prompt tokens we use are [NLG], [NLU] and [S2S]. This information is in the appendix. NLG corresponds to X-denoisers, NLU to R-denoisers and S2S to S-Denoisers.

**Comment by DanielHesslow** [comment]
Thanks, the issue is that ` [NLG]`, `[NLU]` and `[S2S]` are not defined in the default t5 tokenizer. And I can't seem to find any publicly released tokenizer where they are defined. 

Well, unless eg. `[S2S]` is supposed to be tokenized as the sequence [784, 134, 357, 134, 908]

**Comment by vanzytay** [comment]
yeah they are not literally one token per se. it's just a mode prefix.

**Comment by DanielHesslow** [comment]
Ahh okay thanks! This phrasing in the paper confused me `we feed the model an extra paradigm token`, then everything should be good :)

**Comment by DanielHesslow** [comment]
@chessgecko, @felix-schneider my HF port of the model is available here: https://huggingface.co/Seledorn/ul2

**Comment by vanzytay** [comment]
@DanielHesslow gotcha, thanks for pointing out. we'll update the paper in the next version to reflect this so as to not confuse others too! thanks!
