### ISSUE TITLE
[kws streaming] how to increase performance of gpus

### ISSUE THREAD

**Issue by dungnguyen98** [google-research/google-research#1139]
Hi. Thanks for greate repository.
I train kws on my dataset. I check logs and see program have loaded gpus.
But I noticed that sometimes, my gpus are idle (gpus usage down to 0%). I think this is because data loading is not responsive to gpus. 
how can I increase the number of cores in data loading ?

**Comment by rybakov** [comment]
Hi @dungnguyen98, kws models are small and not compute heavy, you could add data prefetching, or increase batch size as discussed in [thread](https://github.com/google-research/google-research/issues/679).

**Comment by dungnguyen98** [comment]
Thank you.
