### ISSUE TITLE
Request for upgrade rouge-score on pypi

### ISSUE THREAD

**Issue by StevenTang1998** [google-research/google-research#1199]
@peterjliu Hi, I see the rouge has been updated many times in the [repository](https://github.com/google-research/google-research/tree/master/rouge). So may you upgrade it on pypi for researchers' convenient use.

Thanks!

**Comment by lvwerra** [comment]
Indeed, a release would be much appreciated!

**Comment by StevenTang1998** [comment]
Thanks!!!

**Comment by lvwerra** [comment]
There seems to be an issue with the release: https://github.com/google-research/google-research/issues/1212

**Comment by peterjliu** [comment]
Whoops, try 0.0.8

**Comment by peterjliu** [comment]
Should be fixed in 0.1.2.
