### ISSUE TITLE
Question on "pse" ( Contrastive behavioral similarity embeddings for generalization in reinforcement learning)

### ISSUE THREAD

**Issue by Wangjw6** [google-research/google-research#1234]
Hi @agarwl ,
I have a question on this paper [Contrastive behavioral similarity embeddings for generalization in reinforcement learning](https://agarwl.github.io/pse/). When you select the negative and positive pairs by the defined PSM and use contrasive loss function. How do you ensure the positive pair is valid? For example, as you sample pairs randomly, it is likely that all sampled pairs are not similar, but you have to select the most similar one among them as positive pair.

Best,
Jiawei

**Comment by agarwl** [comment]
The PSM distance over pairs is computed across all states in two trajectories {x}_{i=1 to N} and {y}_^{j=1 to M}, which gives a pairwise similarity matrix S, where S_{ij} = PSM (x_i, y_j). For each of the rows / columns, we pick the pair with the smallest distance as positive pair while rest as negative pair.  This pair is valid for a given state in first trajectory relative to all states in the other trajectory. This seemed like a reasonable enough approximation and worked reasonably.

**Comment by Wangjw6** [comment]
Thanks for the kind response!
Sorry, maybe I didn't make it clear. I wonder what if there are no similar
states among the two trajectories at all? In this case, there should be no
positive pairs, but according to PSM, you must determine one positive pair
by selecting the smallest one to calculate the contrastive loss.

Rishabh Agarwal ***@***.***> 于2022年8月10日周三 10:54写道：

**Comment by agarwl** [comment]
So, the above approximation was based on the assumption that there states in the environment that are behaviorally similar. If this assumption doesn't hold, then PSM may not capture the right kind of state similarity.

**Comment by Wangjw6** [comment]
Thanks. Then if is there a mechanism to ensure the existence of similar
state pair when selecting the trajectories?

Rishabh Agarwal ***@***.***> 于2022年8月10日周三 15:06写道：

**Comment by Wangjw6** [comment]
Thanks for the clarification!

Best,
Jiawei

Rishabh Agarwal ***@***.***> 于2022年8月10日周三 15:13写道：

**Comment by Wangjw6** [comment]
Can I ask another question? Do we have to sample two trajectories whose
(s,s', a,r) are in order? What if we randomly select  (s,s', a,r) from two
tasks? Like batch1 for task1 and batch2 for task2, then calculate the
contrastive loss based on batch1 and batch2.

Rishabh Agarwal ***@***.***> 于2022年8月10日周三 15:13写道：

**Comment by agarwl** [comment]
Calculating the PSM metric requires the trajectory. If you have access to the metric values, you can sample minibatches.

**Comment by Wangjw6** [comment]
Thank you for the clarification.

Rishabh Agarwal ***@***.***> 于2022年8月10日周三 15:26写道：
