### ISSUE TITLE
[MultigameDT] Unable to initialize multigame decision transformer on Colab

### ISSUE THREAD

**Issue by zwcolin** [google-research/google-research#1247]
Hi,

I was trying to play with the multigame decision transformer notebook on colab (i.e. https://github.com/google-research/google-research/blob/master/multi_game_dt/Multi_game_decision_transformers_public_colab.ipynb) but the runtime crashes whenever the line of code `init_params, init_state = model_fn.init(rng, dummy_datapoint)` is executed. The log did not report anything informational at the time of the crash:

Aug 19, 2022, 11:48:19 AM | WARNING | WARNING:root:kernel 402f5699-0e26-4cef-a58c-dfd68b89e706 restarted
-- | -- | --
Aug 19, 2022, 11:48:19 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports

The model parameters seem to be loaded successfully by displaying
> loading checkpoint from: gs://rl-infra-public/multi_game_dt/checkpoint_38274228.pkl
Number of model parameters: 1.98e+08

However, there was a warning that said:

Aug 19, 2022, 11:46:29 AM | WARNING | 2022-08-19 18:46:29.161081: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "NOT_FOUND: Error executing an HTTP request: HTTP response code 404".
-- | -- | --

To provide more information for debugging, I'm a Colab Pro user and I used TPU runtime with standard memory allocation. The TPU runtime with high RAM allocation crashed too. The notebook is unmodified and I ran it cell by cell. I also tried restarting the runtime after installing all packages but it did not work as well.

I'd really appreciate if someone could look into the error and help fix it. Thank you!

**Comment by henrykmichalewski** [comment]
Hi, I am sorry for this issue. It is not related to this colab - see https://github.com/googlecolab/colabtools/issues/3009 for a minimal repro.

**Comment by debajoy** [comment]
Hi is there a checkpoint file here?
I am not able to see, hence how to run the code?
