### ISSUE TITLE
Dreamfields: Bad results compared to figures in the paper

### ISSUE THREAD

**Issue by hanhung** [google-research/google-research#1248]
Hello,

I have been running some teaser prompts from the Dream Fields site: https://ajayj.com/dreamfields. However, the results seems to be much worse compared to the figures in the paper. I am using the config/config_mq.py default settings. Is this because of the lower resolution (168*168) used in training or are the figures in the paper generated using the LiT-B/32 model instead of ViT-B/16?

I attached results I got for "a sculpture of a rooster.", "a robotic dog. a robot in the shape of a dog." and "matte painting of a bonsai tree; trending on artstation.".

Thanks

https://user-images.githubusercontent.com/18273944/185828051-fa7c41f4-e4d3-45a0-b2fe-a184f82e936a.mp4

https://user-images.githubusercontent.com/18273944/185828067-27a10466-9c14-4444-b1ba-be6959bbf7a6.mp4

https://user-images.githubusercontent.com/18273944/185828078-995f4b65-ec3c-4118-b8aa-d9ced958891c.mp4

!

**Comment by mln-wave** [comment]
Hi @hanhung 
Why did u close this thread? Were you able to reproduce with good results?
