### ISSUE TITLE
[UL2] Smaller model checkpoint request

### ISSUE THREAD

**Issue by yaysummeriscoming** [google-research/google-research#1272]
I'd love to use UL2, however the 20B model is far too big for my application. Section 4 of the paper mentions that multiple smaller models were trained. Could we please get access? Just the best performing model that was used as a base design for the 20B model would be fine. Additionally, a model around the size of T5-small would be great.

**Comment by danecor** [comment]
I'd also love to have access to the checkpoints from the smaller versions of the model.
