### ISSUE TITLE
[pse]Fail to fix seed

### ISSUE THREAD

**Issue by dibbla** [google-research/google-research#1288]
Hi, @agarwl. I'm been using the repo for a while, and I recently found out that I failed to fix seeds. When running the code with `--seed xx`, I can see different versions of results. I tried to install `tensorflow-determinism`, but the library is not working as expected.

I'm using TF2.5 with CUDA10.1.

Any idea? 😕

**Comment by agarwl** [comment]
So, fixing random seeds in TF is possible but has a significant speed & engineering cost (as you have to switch to deterministic ops) and use libraries like the one you mentioned. That said, you can possibly fix the random seeds of the environment and other things (but GPU randomness would still remain).

Re evaluation, I'd say that you can utilize the library in [agarwl.github.io/rliable](agarwl.github.io/rliable) (NeurIPS'21 best paper) and simply report aggregate metrics with 95% CIs as they capture the uncertainty in results. See the section on reporting results on DM Control 100k/ 500k in the paper and hopefully you can utilize some of those protocols for reporting results with small uncertainty. Does that help?

**Comment by dibbla** [comment]
> So, fixing random seeds in TF is possible but has a significant speed & engineering cost (as you have to switch to deterministic ops) and use libraries like the one you mentioned. That said, you can possibly fix the random seeds of the environment and other things (but GPU randomness would still remain).
> 
> Re evaluation, you can utilize the library in [agarwl.github.io/rliable](https://agarwl.github.io/rliable) (NeurIPS'21 best paper) and simply report aggregate metrics with 95% CIs as they capture the uncertainty in results. See the section on reporting results on DM Control 100k/ 500k in the paper and hopefully you can utilize some of those protocols for reporting results with small uncertainty. Does that help?

Yes, it seems fixing randomness on GPU is hard. And the library, judging from the latest uppdate date, is obviously out-of-date. Thanks for your information! I'll go & check it out.
