### ISSUE TITLE
do predict SQUAD : 'NoneType' object has no attribute 'EncodeAsPieces'

### ISSUE THREAD

**Issue by nhocqn** [google-research/google-research#138]
When inference. I got this error:

> WARNING:tensorflow:From /content/google-research/albert/lamb_optimizer.py:34: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1333: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1165: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
> 
> W1117 16:29:12.304847 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:1165: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1165: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.
> 
> W1117 16:29:12.305077 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:1165: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.
> 
> WARNING:tensorflow:From /content/google-research/albert/modeling.py:116: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.
> 
> W1117 16:29:12.305286 140072459204480 module_wrapper.py:139] From /content/google-research/albert/modeling.py:116: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1171: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.
> 
> W1117 16:29:12.306269 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:1171: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.
> 
> WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f64ecc90488>) includes params argument, but params are not passed to Estimator.
> W1117 16:29:14.673645 140072459204480 estimator.py:1994] Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f64ecc90488>) includes params argument, but params are not passed to Estimator.
> INFO:tensorflow:Using config: {'_model_dir': 'gs://bilacac/albert/squad/no_shuffled_zalo_train_with_answers100000_raw.json_32bsz_3', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> cluster_def {
>   job {
>     name: "worker"
>     tasks {
>       key: 0
>       value: "10.34.45.178:8470"
>     }
>   }
> }
> isolate_session_state: true
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f64ebb89d30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.34.45.178:8470', '_evaluation_master': 'grpc://10.34.45.178:8470', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': <tensorflow.python.distribute.cluster_resolver.tpu_cluster_resolver.TPUClusterResolver object at 0x7f64ebb89390>}
> I1117 16:29:14.674898 140072459204480 estimator.py:212] Using config: {'_model_dir': 'gs://bilacac/albert/squad/no_shuffled_zalo_train_with_answers100000_raw.json_32bsz_3', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
> cluster_def {
>   job {
>     name: "worker"
>     tasks {
>       key: 0
>       value: "10.34.45.178:8470"
>     }
>   }
> }
> isolate_session_state: true
> , '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f64ebb89d30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': 'grpc://10.34.45.178:8470', '_evaluation_master': 'grpc://10.34.45.178:8470', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': <tensorflow.python.distribute.cluster_resolver.tpu_cluster_resolver.TPUClusterResolver object at 0x7f64ebb89390>}
> INFO:tensorflow:_TPUContext: eval_on_tpu True
> I1117 16:29:14.675387 140072459204480 tpu_context.py:220] _TPUContext: eval_on_tpu True
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:264: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
> 
> W1117 16:29:14.676191 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:264: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1262: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.
> 
> W1117 16:29:14.706956 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:1262: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:1103: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.
> 
> W1117 16:29:14.844320 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:1103: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.
> 
> WARNING:tensorflow:From google-research/albert/run_squad_sp.py:355: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.
> 
> W1117 16:29:14.846428 140072459204480 module_wrapper.py:139] From google-research/albert/run_squad_sp.py:355: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.
> 
> INFO:tensorflow:Converting 0/2678 pos 0 neg 0
> I1117 16:29:14.846674 140072459204480 run_squad_sp.py:356] Converting 0/2678 pos 0 neg 0
> Traceback (most recent call last):
>   File "google-research/albert/run_squad_sp.py", line 1333, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "google-research/albert/run_squad_sp.py", line 1284, in main
>     output_fn=append_feature)
>   File "google-research/albert/run_squad_sp.py", line 361, in convert_examples_to_features
>     example.question_text, lower=FLAGS.do_lower_case))
>   File "/content/google-research/albert/tokenization.py", line 145, in encode_ids
>     pieces = encode_pieces(sp_model, text, return_unicode=False, sample=sample)
>   File "/content/google-research/albert/tokenization.py", line 113, in encode_pieces
>     pieces = sp_model.EncodeAsPieces(text)
> AttributeError: 'NoneType' object has no attribute 'EncodeAsPieces'

**Comment by Rachnas** [comment]
You need to specify --spm_model_file. Point it to 30k-clean.model.

**Comment by nhocqn** [comment]
> You need to specify --spm_model_file. Point it to 30k-clean.model.

Thank you Rachnas, how can i preprocess data for squad finetuning?
