### ISSUE TITLE
SQUAD : ValueError: '[SEP]' is not in list 

### ISSUE THREAD

**Issue by nhocqn** [google-research/google-research#143]
I got this message when do predicting :
> Traceback (most recent call last):
>   File "google-research/albert/run_squad_sp.py", line 1333, in <module>
>     tf.app.run()
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "google-research/albert/run_squad_sp.py", line 1326, in main
>     output_nbest_file, output_null_log_odds_file)
>   File "google-research/albert/run_squad_sp.py", line 929, in write_predictions
>     doc_offset = feature.tokens.index("[SEP]") + 1
> ValueError: '[SEP]' is not in list

**Comment by steindor** [comment]
I am experiencing the same problem with SQuAD 2. How did you solve this?
