### ISSUE TITLE
How to get whole embedding of TRILLsson model.

### ISSUE THREAD

**Issue by nekosan314** [google-research/google-research#1442]
Hi, I want to use TRILLsson model and extract output embedding, so I check this TensorFlow Hub repository(https://tfhub.dev/google/nonsemantic-speech-benchmark/trillsson5/1). 
However, it enable me to get only one vector which dimension is 1024 regardless of audio data length(I think this vector may be output of CLS token), I want to whole output embedding which include data length. So wanted data shape is like (batch, length, dimension).
I also see this repository ```google-research/tree/master/non_semantic_speech_benchmark/trillsson```, but I don't know hot to solve this problem.
Please tell me the way to get whole embedding vector of TRILLsson.

**Comment by ShreyaPrabhu** [comment]
Hello @nekosan314 Was this question answered? Did you figure out how to get whole embedding vector of TRILLsson? I am also looking for temporal audio feature generation.

**Comment by nekosan314** [comment]
I'm sorry but I also haven't get solution of this problem.

**Comment by Shankar203** [comment]
hi, maybe you can try this,

https://tfhub.dev/google/nonsemantic-speech-benchmark/trillsson1/1
```
# TF2 version
import tensorflow as tf
import tensorflow_hub as hub

m = hub.KerasLayer('https://tfhub.dev/google/trillsson1/1')
# NOTE: Audio should be floats in [-1, 1], sampled at 16kHz. Model input is of
# the shape [batch size, time].
audio_samples = tf.zeros([3, 64000])
embeddings = m(audio_samples)['embedding']```

**Comment by nekosan314** [comment]
Thank you for your answer, but I think this output embeddings is not whole embedding vector. 
I want to get embeddings like (batch, length, dimension), which include time-series outputs.

**Comment by BaMarcy** [comment]
Hi, don't you know how to convert trillsson to ONNX then get the embedding?

**Comment by mbnsfr** [comment]
hi you can use this code :
````
freeze=True
model_path='...'
model=tf.keras.models.load_model(model_path)
# can get layers trainable, name, weights
for layer in model.layers:
    layer.trainable = not freeze

# optional
new_model = tf.keras.Sequential([model])
new_model.add(tf.keras.layers.Dense([512], activation='relu'))
new_model.add(tf.keras.layers.Dense(output_dim, activation='softmax'))

optimizers = {
    'adam': tf.keras.optimizers.Adam,
    'adamw': tf.keras.optimizers.AdamW,
    'adadelta': tf.keras.optimizers.Adadelta,
    'sgd': tf.keras.optimizers.SGD
}
if optimizer not in optimizers:
    raise ValueError("Unsupported optimizer type")
opt = optimizers[optimizer](learning_rate=learning_rate)
new_model.compile(loss=loss, optimizer=opt, metrics=metrics)

# prepare data 
epochs=20
x_train=...
y_train =...
x_test=...
y_test=...
x_val=...
y_val=...
callbacks = [...]

# evaluate and test
train_results = new_model.model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=epochs, verbose=0, callbacks=callbacks)
test_results = new_model.model.evaluate(x_test, y_test, verbose=0)

````
and this can help to use google-research repository [link](https://github.com/huggingface/transformers/issues/17339) 
if you wanna check info of layers inside keras layer of trillsson(which are resnet/efficientNet/ast) the only way is to check variables inside keras_layer of trillsson.
you can find all trillsson model  [here](https://www.kaggle.com/models/google/trillsson)
and this is my [colab](https://colab.research.google.com/drive/1DU9NTgOejpIEy6mdWjG3Neg9jegObNA7?usp=sharing) on how to use model in different ways
just in case this is [link](https://www.kaggle.com/models/google/nonsemantic-speech-benchmark) to trill/filll and distilled versions of them if you wanted to check out

**Comment by nekosan314** [comment]
hi @mbnsfr thank you for your answering!
I am glad you explained it very carefully.
I will refer to your explanation. Thank you very much!
