### ISSUE TITLE
MUSIQ input tensor shape has DataType string which not support in Tensorflow Lite

### ISSUE THREAD

**Issue by GavinXiangPlanetArt** [google-research/google-research#1573]
We converted saved model from https://tfhub.dev/google/musiq/spaq/1 to tflite, and try to integrate to Swift project but failed. Because this model defined input type is string and not supported in Tensorflow Lite. 
Would you please provide me the saved model with spaq which defined input shape which data type is image bytes such as [1 224 224  3] <class 'numpy.float32'> and outputs likes [ 1 1] <class 'numpy.float32'> to define MOS score.
Thanks a million!

**Comment by jason-Ii** [comment]
@GavinXiangPlanetArt  What was the resolution?
