### ISSUE TITLE
kws_streaming post-processing to detect keywords

### ISSUE THREAD

**Issue by naomibb** [google-research/google-research#1580]
hi @rybakov 

I trained svdf model and get great accuracy on the streaming mode and It takes the end of word as the output.
(I used tflite_stream_state_external_model_accuracy function)

Now I want to do post-processing to detect keywords. 
I just know to look the maximum value in out_tflite
but I don't know how to set the threshold value and how to confirm that it is the local maximum value

Are there any methods or suggestions you have?

Thanks

**Comment by rybakov** [comment]
@naomibb similar question was discussed in [link](https://github.com/google-research/google-research/issues/809#issuecomment-940908231). Threshold can depend on your criteria, e.g. optimize precision vs recall; or False accept rate vs miss rate as in [paper](https://assets.amazon.science/7e/94/b850e377478fada03a82751f5535/low-bit-quantization-and-quantization-aware-training-for-small-footprint-keyword-spotting.pdf)
