### ISSUE TITLE
Please release scann compiled against Tensorflow 2.12

### ISSUE THREAD

**Issue by IzakMaraisTAL** [google-research/google-research#1594]
The latest [release (1.2.9)](https://github.com/google-research/google-research/blob/master/scann/docs/releases.md) of scann is compiled against Tensorflow 2.11.

I want to use scann with TFX. The latest [TFX release (1.13.0) ](https://github.com/tensorflow/tfx/releases)requires Tensorflow >=2.12.0. This makes it impossible to use scann with TFX 1.13.0. 

TFX 1.13.0 is also the first one to ship a docker image with python > 3.7. Since [python 3.7 security support ends 27 June](https://endoflife.date/python), I really want to use latest TFX docker image, but my project requires that I also install scann.

This would also address: https://github.com/google-research/google-research/issues/1569
 
@sammymax I see you most recently edited the release notes. Is there a chance that you could take a look at this please?

**Comment by IzakMaraisTAL** [comment]
Python 3.7 is now past end of life, so we would like to move on to the 3.9 based TFX 1.13 Docker image.

Also, https://github.com/tensorflow/tfx/issues/5777#issuecomment-1640564951 requests that I test a bug fix with TFX 1.13, but this issue is blocking that test.

**Comment by NiclasLindqvist** [comment]
There seems to have been an oversight in the latest release, stating to support 2.12 but requiring 2.13 in the install. I recon it's a hassle to reverse the requirements of that release, so I updated the releases.md instead in #1719 . Not sure if that helps you at all?

**Comment by IzakMaraisTAL** [comment]
Thanks for the update and correction. 

The TFX 1.13.0 (latest) release still targets tensorflow 2.12 explicitly. I guess we can wait for a future TFX release which will which will hopefully target tensorflow 2.13. Based on the last two releases, the TFX project seems good at not skipping minor tensorflow versions.
