### ISSUE TITLE
[kws_streaming] full INT8 streaming model quantization issue 

### ISSUE THREAD

**Issue by AhmedTElthakeb** [google-research/google-research#1613]
Hello @rybakov , 

Is it possible to get a fully INT8 quantized tflite for STREAM_EXTERNAL_STATE and STREAM_INTERNAL_STATE models?

For example: [ds_tc_resnet](https://github.com/google-research/google-research/blob/master/kws_streaming/models/ds_tc_resnet.py)
By adding a calibration set, I can get fully INT8 model for non-stream case using PTQ. But, not sure how to pass calibration set for streaming scenarios, any guidance?

If I use QAT [(ds_tc_resnet_qat_test),](https://github.com/google-research/google-research/blob/master/kws_streaming/models/ds_tc_resnet_qat_test.py) I can get tflite model but with Quantize/Dequantize between ops, is there a way to remove these and export only INT8 tflite model?

Thanks

**Comment by rybakov** [comment]
Hello @AhmedTElthakeb,

TFLite converter in [utils.py](https://github.com/google-research/google-research/blob/cd76f8373df19f3268d150c467cf4d9241b7017b/kws_streaming/models/utils.py)
with parameters:
```
  converter.experimental_new_quantizer = True
  converter.experimental_enable_resource_variables = True
  converter._experimental_variable_quantization = True
```
should remove Quantize/Dequantize between ops (at least between streaming states) for streaming with internal state.
You will need to train ds_tc_resnet with QAT as in example test for [ds_tc_resnet](https://github.com/google-research/google-research/blob/master/kws_streaming/models/ds_tc_resnet_qat_nbit_test.py)
Not that this feature is experimental.

There are two examples with streaming model calibration: [cnn_nbit_test.py](https://github.com/google-research/google-research/blob/cd76f8373df19f3268d150c467cf4d9241b7017b/kws_streaming/models/cnn_nbit_test.py) and [cnn_test.py](https://github.com/google-research/google-research/blob/cd76f8373df19f3268d150c467cf4d9241b7017b/kws_streaming/models/cnn_test.py). Both are designed for calibrating model with external streaming states. But in this example inputs for streaming states will stay in float.

For internal streaming state the test would be the same, but calibration data will have only input data (no need to feed input streaming states). Also will need to above flags (_experimental_variable_quantization, experimental_new_quantizer, experimental_enable_resource_variables).
These features are experimental.

**Comment by ctwillson** [comment]
@AhmedTElthakeb Could u provide your requirements.txt?I cannot run the code
