### ISSUE TITLE
Cannot download RICO dataset

### ISSUE THREAD

**Issue by RyanJayWu** [google-research/google-research#1626]
Hi there,

I was trying to download complete RICO dataset, but I found I cannot open the [website](http://interactionmining.org/rico#quick-downloads). 

Could someone provide a web page where I can download the complete RICO dataset?

Cheers,
Ryan

**Comment by halimaqadah** [comment]
https://www.kaggle.com/datasets/onurgunes1993/rico-dataset

**Comment by RyanJayWu** [comment]
> https://www.kaggle.com/datasets/onurgunes1993/rico-dataset

Hi halimaqadah,

I checked this dataset, but it doesn't contain interaction traces. I hope to download the complete RICO dataset. But anyway, thanks for your answer.

Cheers,
Ryan

**Comment by RyanJayWu** [comment]
ah, i can open the RICO home page now.
