### ISSUE TITLE
Asymmetric Noise Addition on Covariance Matrices

### ISSUE THREAD

**Issue by shuaitang** [google-research/google-research#1631]
https://github.com/google-research/google-research/blob/master/private_kendall/boosted_adassp.py#L113

Hi, thanks for implementing Boosted AdaSSP, and comparing our proposed approach with Tukey. 

I, however, noticed that the noise addition on the covariance matrix would lead to an asymmetric noisy matrix, which is inconsistent with the implementation of AdaSSP here: https://github.com/yuxiangw/autodp/blob/master/tutorials/tutorial_AdaSSP_vs_noisyGD.ipynb. 

@mgtjoseph Could you please take a look? Thanks,

Shuai

**Comment by mgtjoseph** [comment]
Good point. We copied our implementation off Algorithm 1 in https://arxiv.org/abs/2303.03451 and didn't notice the point about symmetric noise in the proof of Theorem A.3.

I re-ran the k=5 BAS, L-BAS, and K-BAS experiments with the symmetric noise fix and didn't see a significant change in the R^2 values or the resulting rankings relative to the other methods, so I don't think this bug meaningfully affects the experiment conclusions. Nonetheless, we'll include this fix in the next code update.

**Comment by shuaitang** [comment]
sounds good. thanks!!

**Comment by shuaitang** [comment]
sounds good. thanks!!
