### ISSUE TITLE
Rouge-L: Large differences to pyrouge/Rouge 1.5.5

### ISSUE THREAD

**Issue by amarfurt** [google-research/google-research#168]
I have evaluated the checkpoint of the paper [Text Summarization with Pretrained Encoders](https://arxiv.org/abs/1908.08345) with the pyrouge and the rouge-score packages. I observe rather large differences, especially for Rouge-L:

With pyrouge:
```
rouge_1_f_score      0.42164
rouge_2_f_score      0.19486
rouge_l_f_score      0.39156
```

With rouge-score:
```
rouge_1_f_score      0.43707
rouge_2_f_score      0.20137
rouge_l_f_score      0.30160
```

My procedure: The `validate` mode of the authors' code ([Github](https://github.com/nlpyang/PreSumm)) extracts candidate and reference summaries in text format. I then pass these to the authors' `test_rouge` function ([link](https://github.com/nlpyang/PreSumm/blob/ce8dc017fbef7c12b1b4bd764f0c3d20911ead5e/src/others/utils.py#L54)) (which to my understanding does no further processing except for preparing the file structure for pyrouge). For the rouge-score package I used the following code:
```python
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
aggregator = BootstrapAggregator()
candidates = [line.strip() for line in open(candidates_path, encoding='utf-8')]
references = [line.strip() for line in open(references_path, encoding='utf-8')]
assert len(candidates) == len(references)
for i, (c, r) in enumerate(zip(candidates, references)):
  aggregator.add_scores(scorer.score(r, c))
results = aggregator.aggregate()
```

Things I've checked:
- There are no empty lines in candidate or reference summaries (after `.strip()`)
- The other flags passed to pyrouge/Rouge-1.5.5 are equal 
- This behavior is consistent with different random seeds

**Comment by nlpyang** [comment]
the main difference should be sentence splitting, in PreSumm, there is a <q> token to indicate sentence boundaries, while in rouge-score splits sentences by newline.  Rouge-L is very sensitive to sentence splitting.

**Comment by amarfurt** [comment]
I didn't see this, thanks. If I replace the `<q>` token with a newline character and use the "rougeLsum" type, I get results that are close enough.

Updated scores:
```
rouge_1_f_score      0.41897
rouge_2_f_score      0.19420
rouge_lsum_f_score   0.38942
```

Updated code:
```python
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeLsum'], use_stemmer=True)
aggregator = BootstrapAggregator()
candidates = [line.strip() for line in open(candidates_path, encoding='utf-8')]
references = [line.strip() for line in open(references_path, encoding='utf-8')]
assert len(candidates) == len(references)
for i, (c, r) in enumerate(zip(candidates, references)):
  c = c.replace('<q>', '\n')
  r = r.replace('<q>', '\n')
  aggregator.add_scores(scorer.score(r, c))
results = aggregator.aggregate()
```
