### ISSUE TITLE
Problem with running demo in F-VLM

### ISSUE THREAD

**Issue by aakb101** [google-research/google-research#1729]
Hi, thanks for your great contributions @ https://github.com/google-research/google-research/tree/master/fvlm @weichengkuo   I'm getting this error after running python3 demo.py --model=resnet_50:

`  File "/home/anaconda3/envs/fvlm/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/anaconda3/envs/fvlm/lib/python3.11/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 301, in restored_function_body
    raise ValueError(
ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (1 total):
    * {'image': <tf.Tensor 'inputs_1:0' shape=(1, 1024, 1024, 3) dtype=bfloat16>,
 'text': <tf.Tensor 'inputs:0' shape=(1, 30, 1024) dtype=float32>}
  Keyword arguments: {}

 Expected these arguments to match one of the following 1 option(s):

Option 1:
  Positional arguments (1 total):
    * {'image': TensorSpec(shape=(1, 1024, 1024, 3), dtype=tf.bfloat16, name='image'),
 'text': TensorSpec(shape=(1, 91, 1024), dtype=tf.float32, name='queries')}
  Keyword arguments: {}
`

Could you please help me to get it working?

**Comment by weichengkuo** [comment]
Thanks for the report. From the error, it looks like the default max number classes was not set correctly. Could you verify if it works when you run:
python3 demo.py --model=resnet_50 --max_num_classes=91

**Comment by aakb101** [comment]
That worked, thanks!

**Comment by weichengkuo** [comment]
Great, thanks for verifying. Will send a fix soon.

**Comment by earl-juanico** [comment]
@weichengkuo, thank you. I also confirm that this was the command modification needed to run the demo code. I am a grad student and very interested in confirming the results reported. I was able to confirm the evaluation on COCO using the precomputed embeddings provided. I also wish to confirm the evaluation on LVIS. Would it be possible for you to upload the precomputed embeddings for LVIS 1.0?
