### ISSUE TITLE
MADLAD-400 Checkpoints and Data are not available

### ISSUE THREAD

**Issue by xhluca** [google-research/google-research#1738]
When I click on one of the links, I get the following page:

![image](https://github.com/google-research/google-research/assets/21180505/fecb690e-8c0c-42ca-9637-c06803373179)

It seems the data is not publicly accessible, I presume due to configuration errors.

**Comment by axelmukwena** [comment]
@xhluca The data is now available
<img width="1138" alt="Screenshot 2023-09-13 at 8 41 40 PM" src="https://github.com/google-research/google-research/assets/20848898/ea171961-5d45-4026-b9ea-d15c9315527d">

**Comment by xhluca** [comment]
Thanks!

**Comment by qunash** [comment]
That's just the checkpoints and not the dataset iiuc

**Comment by ChingYoung** [comment]
Where to download the data set

**Comment by AsmaaAlagha** [comment]
How i can  download the dataset and model MADLAD-400

**Comment by tom9358** [comment]
> Where to download the data set

Here: https://huggingface.co/datasets/allenai/MADLAD-400
