### ISSUE TITLE
[ROVIT] How to generate Figure 3 in the paper "Region-Aware Pretraining for Open-Vocabulary Object Detection with Vision Transformers"

### ISSUE THREAD

**Issue by buzuyun** [google-research/google-research#1744]
I am confused about how to generate Figure 3 in the paper "Region-Aware Pretraining for Open-Vocabulary Object Detection with Vision Transformers". The figure shows the brightness patterns of the learned positional embeddings for the ViT-B/16 backbone.

According to my understanding, each tile in the figure represents the cosine similarity between the positional embedding of one patch and the positional embeddings of all other patches. **Therefore, I would expect each tile to contain a single value. However, the figure shows that each tile contains multiple values.**

I am wondering why each tile contains multiple values. Is it because the cosine similarity between two vectors is a vector? If so, how do I interpret the values in each tile?

Can you please provide the code for generating Figure 3 in the paper?
![image](https://github.com/google-research/google-research/assets/95299781/d521a1de-3086-4320-adac-e9609fe1367a)

**Comment by mcahny** [comment]
Thanks for the question @buzuyun. So for example in the top-left tile, we visualize the similarity value between the positional embedding (PE) of the top-left location (1xD) and PEs of all other locations (14x14xD) which results in the 14x14 values. Hope this helps clarifying.

**Comment by buzuyun** [comment]
Thanks! It is helpful! :)
