### ISSUE TITLE
can't run TFT example

### ISSUE THREAD

**Issue by cometta** [google-research/google-research#175]
when i try to run the training on gpu , i get below error

> 2020-01-05 17:25:08.166159: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
> 2020-01-05 17:25:08.384437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-01-05 17:25:09.025964: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2020-01-05 17:25:09.026043: F tensorflow/core/kernels/cudnn_rnn_ops.cc:1643] Check failed: stream->parent()->GetRnnAlgorithms(&algorithms) 
> Aborted (core dumped)

i'm using tensorflow-gpu ver 1.5.0, cudnn 7.6.5.32, cuda 10

**Comment by akeskiner** [comment]
@cometta I'm facing the same issue. How did you solve this?
