### ISSUE TITLE
instruction_following_eval: master branch code broken

### ISSUE THREAD

**Issue by nlpcat** [google-research/google-research#1856]
```
raise ValueError("prompt_to_repeat must be set.")
ValueError: prompt_to_repeat must be set.
```
the master branch can not run successfully since it can't handle the prompt_to_repeat correctly. 

cc @lehougoogle

**Comment by lehougoogle** [comment]
Hi @nlpcat
The bug should have been fixed now.

**Comment by lehougoogle** [comment]
Thanks for the feedback. Now the demo response jsonl is fixed.
