### ISSUE TITLE
[slot attention] slots spread over all objects

### ISSUE THREAD

**Issue by franciscocms** [google-research/google-research#1928]
what would you recommend for a case where slots do not converge for a slot-object binding, but all slots (except for background ones) end up encoding information from all objects?? if I am not seeing this wrong, softmax only forces competition over slots, but does not encourage an object-centric representation for each slot...

**Comment by matthias-brucklacher** [comment]
@franciscocms Thanks for the quick reply, good to know. Although, I am running into this in the object discovery setup.

**Comment by matthias-brucklacher** [comment]
![image](https://github.com/google-research/google-research/assets/99026769/71637f35-b581-4169-89c6-c86d62ccce30)

It's very simple images with a uniform background and three objects consisting of 2x2 pixels in random positions. As you can see, the reconstructions are shared across slots. I tried many different encoders including raw inputs, but the slots never latched onto the objects. What I also tried was to reduce the slot dimensionality to create a bottleneck, thinking that this might avoid encoding the whole scene, but then the model doesn't learn to reconstruct at all.

**Comment by MehdiJmlkh** [comment]
Hi @matthias-brucklacher,

Did you happen to find a solution? I’m facing the same issue and would really appreciate any advice or guidance you could share.

Thanks in advance!
