### ISSUE TITLE
ClusterGCN - Why is AX a dot product op instead of a sparse dense matrix multiplication op?

### ISSUE THREAD

**Issue by pyyush** [google-research/google-research#195]
`if precalc:`
      `train_feats = train_adj.dot(feats)`
      `train_feats = np.hstack((train_feats, feats))`

**Comment by lobsterlooks** [comment]
((hhstack))) is the answer tanks regards michael maindal jensen

**Comment by pyyush** [comment]
First of all why do we have to do a dot product and not a sparse dense matmul? According to the paper shouldn't train_adj be a sparse N x N matrix and feats be a dense N x F matrix?
