### ISSUE TITLE
[depth_from_video_in_the_wild] checkpoints for model trained on YouTube8M

### ISSUE THREAD

**Issue by m3at** [google-research/google-research#200]
Hi, thank you for the great paper and releasing the code for reproducibility.

According to [this comment](https://github.com/google-research/google-research/issues/46#issuecomment-522846228) from an other issue you planned to release the pretrained checkpoints for models trained on YouTube8M. 

Is that still a possibility?  
(I note that we can re-train a model as the YouTube8M IDs used have been published, but the dataset is quite large so a checkpoint would be very helpful for comparing the performances without re-training)

**Comment by gariel-google** [comment]
Hi, sorry for the delayed response. We would have to get clearance for that form legal, it turns out to be a bit more complicated than we thought. I hope that the training code and the YouTube8M IDs can be of some help meanwhile...

**Comment by m3at** [comment]
Understood, I hope that the legal department can clear the release in the future.
Meanwhile yes, the training code and IDs are sufficient for reproducibility, thank you.

**Comment by PriyaThakur** [comment]
Hi @gariel-google,
I wanted to know if you got clearance for releasing the pre-trained checkpoints for the model trained on YouTube8M data?

**Comment by gariel-google** [comment]
@PriyaThakur Unfortunately we were unable to get the approval from our legal department to release these checkpoint. I am sorry.
