### ISSUE TITLE
DPOK training running into errors with the prescribed instructions 

### ISSUE THREAD

**Issue by sayakpaul** [google-research/google-research#2142]
@siyangl, I set up an environment for running DPOK exactly following what's described in the README. 

```bash
Traceback (most recent call last):                                                                               | 0/50 [00:00<?, ?it/s]
  File "/fsx/sayak/dpok-experiments/train_online_pg.py", line 1485, in <module>
    main()
  File "/fsx/sayak/dpok-experiments/train_online_pg.py", line 1385, in main
    _collect_rollout(args, pipe, is_ddp, batch, calculate_reward, state_dict)
  File "/fsx/sayak/dpok-experiments/train_online_pg.py", line 836, in _collect_rollout
    ) = pipe.forward_collect_traj_ddim(prompt=batch, is_ddp=is_ddp)
  File "/fsx/sayak/dpok-experiments/pipeline_stable_diffusion_extended.py", line 269, in forward_collect_traj_ddim
    latents, log_prob = self.scheduler.step_logprob(
  File "/fsx/sayak/dpok-experiments/scheduling_ddim_extended.py", line 116, in step_logprob
    alpha_prod_t = self.alphas_cumprod[timestep].to(timestep.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (CPU)
```

Training command:

```bash
accelerate launch train_online_pg.py --p_batch_size 4 --reward_weight 10 --kl_weight 0.01  --learning_rate 1e-5 --single_flag 1 --single_prompt "A green colored rabbit." --gradient_accumulation_steps 12 --clip_norm 0.1 --g_batch_size 10 --multi_gpu 0 --v_flag 1
```

Am I missing anything?

**Comment by sayakpaul** [comment]
Additionally, I find something very weird here:

So, for `multi_gpu` you pass the `unet`: https://github.com/google-research/google-research/blob/902e817277bc0f753270898c90fad31dc3ef17ec/dpok/train_online_pg.py#L1258. But never actually do save_pretrained() on the `unet`.

When `multi_gpu` is not enabled you pass something different: https://github.com/google-research/google-research/blob/902e817277bc0f753270898c90fad31dc3ef17ec/dpok/train_online_pg.py#L1262.

Why is this the case?

**Comment by kjm981995** [comment]
I just add "self.alphas_cumprod = self.alphas_cumprod.to(timestep.device)" at scheduling_ddim_extended.py L118, and it is addressed.

**Comment by siyangl** [comment]
I don't own this project. Please reach Moonkyung Ryu at ***@***.***
