### ISSUE TITLE
depth_from_video_in_the_wild: Variables in motion_field_net not being reused properly

### ISSUE THREAD

**Issue by jenkspt** [google-research/google-research#230]
It appears that some of the variables in the motion_field_net from [google-research/depth_from_video_in_the_wild/motion_prediction_net.py](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py) are not being reused when the the model is initialized for the forward and inverse ego-motion prediction.

When inspecting the variables  using
```
tf_path = os.path.abspath('kitti_learned_intrinsics/model-248900')  
tf_vars = tf.train.list_variables(tf_path)
print(tf_vars)
```
and only considering variables in the scope 'MotionFieldNet'
there are four redundant name spaces:

('MotionFieldNet/compute_loss/MotionFieldNet/...
('MotionFieldNet/compute_loss/MotionFieldNet_1/...
('MotionFieldNet/compute_loss/MotionFieldNet_2/...
('MotionFieldNet/compute_loss/MotionFieldNet_3/...

However when I initialize the model and comment out the second call of motion_field_net (as in the following code block from [google-research/google-research/depth_from_video_in_the_wild/model.py](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/model.py))
```
def _build_egomotion_test_graph(self):
    """Builds graph for inference of egomotion given two images."""
    with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):
      self._image1 = tf.placeholder(
          tf.float32, [self.batch_size, self.img_height, self.img_width, 3],
          name='image1')
      self._image2 = tf.placeholder(
          tf.float32, [self.batch_size, self.img_height, self.img_width, 3],
          name='image2')
      # The "compute_loss" scope is needed for the checkpoint to load properly.
      with tf.name_scope('compute_loss'):
        rot, trans, _, _ = motion_prediction_net.motion_field_net(
            images=tf.concat([self._image1, self._image2], axis=-1))
        """
        inv_rot, inv_trans, _, _ = (
            motion_prediction_net.motion_field_net(
                images=tf.concat([self._image2, self._image1], axis=-1)))
        """
        return
```
restoring from the kitti checkpoint and then re-saving yields only a set of variables under the name scope
('MotionFieldNet/compute_loss/MotionFieldNet/...

without the scopes having the _1, _2 & _3 suffixes, Indicating that these variables are being copied instead of reused. It is my understanding that all of the motion_field_net variables should be reused for the forward and inverse ego-motion prediction.

**Comment by jenkspt** [comment]
Here are the variables names from the [KITTI checkpoint](https://www.googleapis.com/download/storage/v1/b/gresearch/o/depth_from_video_in_the_wild%2Fcheckpoints%2Fkitti_learned_intrinsics.zip?generation=1566493768934649&alt=media).

[kitti_checkpoint_var_names.txt](https://github.com/google-research/google-research/files/4345235/kitti_checkpoint_var_names.txt)

And here are the variable names after using the modified code from the previous comment.
[kitti_checkpoint_var_names_single_init.txt](https://github.com/google-research/google-research/files/4345242/kitti_checkpoint_var_names_single_init.txt)

**Comment by liyingliu** [comment]
Hi, I found the same issue as well. And I also believe reusing these variables is intended. Could you help to explain it? @gariel-google

**Comment by gariel-google** [comment]
Hi liyingliu@ and jenkspt@

I am sorry for the delayed response. Yes, there is a bug here
https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py#L244-L250

which causes some of the variables to not be reused. We fixed it since in
our internal version, but all the numbers we published in the paper were
obtained with that code, and the checkpoints we released are compatible
with that (buggy) code. If we fix the code now, the checkpoints we
published will not reproduce the numbers in the paper.

Perhaps we can publish the corrected version protected by a flag that will
be off by default? Would that help you guys?

**Comment by jenkspt** [comment]
Thanks for the response! Yes this would be helpful.

I would hope reusing the variables properly would improve results and/or reduce training time. However there is always the chance that the bug is actually necessary to achieve the published results.

**Comment by gariel-google** [comment]
From what we tried, the results do reproduce with the fix, and are slightly
better in some cases, but we did not re-run systematically all
the experiments in the paper and we do not have checkpoints for all of
them. We will release the fixed code, hopefully over the next few days.
