### ISSUE TITLE
depth_from_video_in_the_wild: how to represent intrinsics as learned variables

### ISSUE THREAD

**Issue by octpath** [google-research/google-research#245]
@gariel-google 
Thanks for sharing the code about your paper.
I want to implement your method (in TF2), and I have got somewhat good results on KITTI dataset. Now, I'm trying to implement "5.4. Camera intrinsics evaluation". But I don't know how to "represented each intrinsic parameter as a separate learned variable".
Would you share me motion_prediction_net.py (TF1/Slim) that treats intrinsics as trainable_variables?
Thank you in advance.

**Comment by gariel-google** [comment]
Hi octpath@,  we will do our best to release that code too, but meanwhile, here's a snippet of how to do that. If you know that all your frames come from the same camera (which is true for EuRoC but not for KITTI / cityscapes), you'd do something like this

```python
fx = tf.get_variable('fx', initializer=image_width)
fy = tf.get_variable('fy', initializer=image_height)
x0 = tf.get_variable('x0', initializer=image_width * 0.5)
y0 = tf.get_variable('y0', initializer=image_height * 0.5)

intrinsics_mat = tf.convert_to_tenosr([[fx, 0.0, x0], [0.0, fy, y0], [0.0, 0.0, 1.0]])
```

If you have multiple videos, assuming that for each frame / triplet you have a key indicating what video they came from, you can use a tensorflow hash table to keep a separate intrinsic matrix per key. Hope that helps!

**Comment by octpath** [comment]
Thanks for the reply!
I will try it.
And I'm looking forward to the code being released.

**Comment by ikramabdel** [comment]
> Hi octpath@, we will do our best to release that code too, but meanwhile, here's a snippet of how to do that. If you know that all your frames come from the same camera (which is true for EuRoC but not for KITTI / cityscapes), you'd do something like this
> 
> ```python
> fx = tf.get_variable('fx', initializer=image_width)
> fy = tf.get_variable('fy', initializer=image_height)
> x0 = tf.get_variable('x0', initializer=image_width * 0.5)
> y0 = tf.get_variable('y0', initializer=image_height * 0.5)
> 
> intrinsics_mat = tf.convert_to_tenosr([[fx, 0.0, x0], [0.0, fy, y0], [0.0, 0.0, 1.0]])
> ```
> 
> If you have multiple videos, assuming that for each frame / triplet you have a key indicating what video they came from, you can use a tensorflow hash table to keep a separate intrinsic matrix per key. Hope that helps!

Hi 

I'm attempting the same thing , but i'd like to know where to input your suggestion exactly ? Thanks

**Comment by gariel-google** [comment]
@ikramabdel instead of [this](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py#L176) line.

**Comment by ikramabdel** [comment]
> @ikramabdel instead of [this](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py#L176) line.

Thank you! i will try it.

**Comment by VladimirYugay** [comment]
> Thanks for the reply!
> I will try it.
> And I'm looking forward to the code being released.

@octpath do you have the repo to share with 2.0 implementation?
