### ISSUE TITLE
extracting layers from tensor2Tensor models: _layers returns empty

### ISSUE THREAD

**Issue by MarziehLenjani** [google-research/google-research#280]
Hi,

I need to extract the intermediate values after infer. I knew how to do it in Keras, something similar to what is suggested [here](https://keras.io/getting_started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer-feature-extraction). I am using state_of_sparsity folder of this repository. I tried to get the layers using _layers but it returns empty. 

```
translate_model = registry.model(FLAGS.model)(hparams, Modes.EVAL)
tf.print(translate_model._layers)
```
I have posted my question [here](https://stackoverflow.com/questions/61916210/how-can-i-obtain-the-output-of-an-intermediate-layer-feature-extraction-in-tens). I was wondering why _layers returns empty. Is there any other way of cutting tensor2tensor models at a specific layer or extracting intermediate values after infer?

**Comment by vmiheer** [comment]
@MarziehLenjani, how were you able to resolve this issue?

**Comment by MarziehLenjani** [comment]
> @MarziehLenjani, how were you able to resolve this issue?

I did not resolve it. But I guess we should change the graph and add a node that prints values. I
