### ISSUE TITLE
depth_from_video_in_the_wild: scale factor of the predicted translation vector

### ISSUE THREAD

**Issue by liyingliu** [google-research/google-research#286]
@gariel-google
Dear author, Thanks for sharing the source code of the paper. 

I have a question about the scale factor of the predicted translation vector. 
Basically, I tried to use the predicted depth and  the predicted egomotion to warp the image T to image T+1. 
I first project image T using the predicted depth get a 3D pointcloud then use the predicted translation vector, rotation matrix and camera intrinsic to project the 3D pointcloud back to an image space (T+1). However, I can’t get a proper warped image T+1 WITHOUT scaling the translation vector.  After some trial and error, I found that the scale factor for the translation vector is about 0.001. 

Therefore, my question is: do you need such a scaling factor for the translation vector when you try to project image T to image T+1 (or inversely) to compute the reconstruction loss? I am quite confused as I understand the predicted depth’s scale and the predicted egomotion’s scale should be matched and thus we should be able to do reconstruction without scaling those variables.

Any help would be appreciated. Thank you in advance.

**Comment by gariel-google** [comment]
Hi @liyingliu,

Indeed the translation vector is scaled by a learned factor. The code is [here](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py#L171). If you use [motion_field_net](https://github.com/google-research/google-research/blob/master/depth_from_video_in_the_wild/motion_prediction_net.py#L80) directly, and load form the checkpoints, all this should be taken care of for you. 
Hope that helps!
