### ISSUE TITLE
Inference code and models for 'Unprocessing Images for Learned Raw Denoising'

### ISSUE THREAD

**Issue by TouqeerAhmad** [google-research/google-research#29]
Hi, 
I was wondering if you could provide the pre-trained models for CVPR2019 paper title 'Unprocessing Images for Learned Raw Denoising'. I have looked into 'unprocessing' dir, no models or inference code, do you intend to release that or not?

Thanks you!
Touqeer

**Comment by MortenHannemose** [comment]
I can see that it has been committed to the project now.

**Comment by TouqeerAhmad** [comment]
Thank you!

**Comment by Alymostafa** [comment]
@MortenHannemose  can you tell me where is the Inference code for other datasets and how can I use it on different datasets because I don't understand from readme?
