### ISSUE TITLE
【TCC】Why not embed future frames jointly?

### ISSUE THREAD

**Issue by tsuyoshily** [google-research/google-research#296]
I have a question about TCC implementation.
In dataset.py, line 144.
https://github.com/google-research/google-research/blob/541f6d8637effe03994b03d54a9eee7a375bd27f/tcc/datasets.py#L136-L146

"We don't want to encode information from the future. "
Why not embed future frame jointly?
i thought that using future frames make representation better.

i already read tcc paper, but i couldn't figure out the reason.
i hope @debidatta or other professionals give me answear.
Sorry disturb you, thank you.

**Comment by debidatta** [comment]
There is no issue with using future frames for representation learning. It should help.

In some downstream applications, it is not possible to use future  frames (like predicting next action in robotics). To be compatible with both kinds of applications we did not use future frames. 

You can use the following snippet for using information from the future:

```python
steps = tf.range(step - (num_steps - num_steps//2 -1) * stride,
                          step + (num_steps//2 + 1) * stride,
                          stride)
```

**Comment by tsuyoshily** [comment]
Thanks for the quick reply and tips!!
I'm gonna use your snippet : )
