### ISSUE TITLE
when I want to copy a layer, there is a error - 'no inbound_nodes'

### ISSUE THREAD

**Issue by Lebhoryi** [google-research/google-research#297]
The project is KWS-streaming.

In training, it is OK for me. But when trying to convert non-streaming model to streaming model about 'STREAM_INTERNAL_STATE_INFERENCE' state, I have met a problem.

- It convert streaming model failed. The information is follow:
```shell
WARNING: failed to convert to SavedModel: 'Node' object has no attribute 'outputs'
```

My question:
1. How could I  convert non-stream model to stream model successfully?
2. My view as follow is right or not ?If right, how to solve it?

The coding is here:
1. [ test.convert_model_saved](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/train/model_train_eval.py#L162)
2. [utils.model_to_saved(model, flags, path_model, mode)](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/train/test.py#L610)
3. [model = to_streaming_inference()](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/models/utils.py#L369)
4. [model_inference = convert_to_inference_model()](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/models/utils.py#L283)
5. [new_model = _clone_model(model, input_tensors)](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/models/utils.py#L243)
6. [models._clone_layers_and_model_config()](https://github.com/google-research/google-research/blob/c880344f15d2453ab7eccbfea0b259c7019094f6/kws_streaming/models/utils.py#L122)

The problem is in six, there hava something wrong when `clone layer configs`. In my opinion, maybe the question is after copying layers config, the new layers losses the `inbound nodes`, so the new layers not support any  `input` or `output`. The fisrt input layer looks ok beacause it have inbounds nodes. However the others is wrong. 

emm, I could not solve it, need some help. thx

> the pc & training information:
- ubuntu 16.04, tf 2.2.0
```shell
--data_dir ../data \
--lr_schedule linear \
--background_volume 0.1 \
--l2_weight_decay 0.0 \
--background_frequency 0.8 \
--split_data 1 \
--time_shift_ms 100.0 \
--how_many_training_steps 10000,5000 \
--eval_step_interval 400 \
--learning_rate 0.0001,0.00005 \
--batch_size 100 \
--wanted_words yes,no,up,down,left,right,on,off,stop,go \
--train_dir ./speech_commands_train/ \
--save_step_interval 100 \
--start_checkpoint '' \
--resample 0.15 \
--train 1 \
--window_size_ms 40 \
--window_stride_ms 40 \
--dct_num_features 20 \
--preprocess mfcc \
--feature_type mfcc_tf \
--mel_lower_edge_hertz 20.0 \
--mel_upper_edge_hertz 7000 \
--fft_magnitude_squared 0 \
--mel_num_bins 40 \
cnn \
--cnn_filters 64,64,64,64,128,64,128 \
--cnn_kernel_size '(3,3),(5,3),(5,3),(5,3),(5,2),(5,1),(3,1)' \
--cnn_dilation_rate '(1,1),(1,1),(1,1),(1,1),(1,1),(1,1),(1,1)'
```

**Comment by Lebhoryi** [comment]
@peterjliu @rybakov @qlzh727

**Comment by Lebhoryi** [comment]
other question is what the version about tensorflow?

there are some missing files in tf 2.1 or 2.2, but have found in `github tf master`

**Comment by rybakov** [comment]
Hi Lebhoryi,

There was a refactor in Keras which impacting "clone" api. I updated kws lib with new api and bumped up tf version requirements in the [experiments folder](https://github.com/google-research/google-research/tree/master/kws_streaming/experiments), but did not update requirements.txt. Thank you for reporting it! Fix with updated requirements.txt is submitted. 
Please try "pip install tf_nightly==2.3.0.dev20200515" - kws was validated on this version, and let me know if it works for you (tf_nightly should work too).

Step with utils.model_to_saved(model, flags, path_model, mode) is optional, that is why even it fails, only warning is printed.

Best,
Oleg.

**Comment by Lebhoryi** [comment]
After `pip3 install tf_nightly==2.3.0.dev20200515`, it seems Okay now. It could convert non-stream to stream model automaticly without any errors.

Thanks  for updating requirements.txt. It's great.

The final file trees as follow:
```shell
⇒  tree ./train_model/cnn
./train_model/cnn
├── accuracy_last.txt
├── best_weights.data-00000-of-00002
├── best_weights.data-00001-of-00002
├── best_weights.index
├── flags.json
├── flags.txt
├── graph.pbtxt
├── labels.txt
├── last_weights.data-00000-of-00002
├── last_weights.data-00001-of-00002
├── last_weights.index
├── logs
│   ├── train
│   │   ├── events.out.tfevents.1591857342.ubuntu
│   │   ├── events.out.tfevents.1591857494.ubuntu
│   │   ├── events.out.tfevents.1591870751.RT-AI
│   │   └── events.out.tfevents.1591875621.ubuntu
│   └── validation
│       ├── events.out.tfevents.1591857855.ubuntu
│       └── events.out.tfevents.1591870970.RT-AI
├── model_summary.txt
├── non_stream
│   ├── assets
│   ├── model_summary.txt
│   ├── saved_model.pb
│   └── variables
│       ├── variables.data-00000-of-00002
│       ├── variables.data-00001-of-00002
│       └── variables.index
├── quantize_opt_for_size_tflite_non_stream
│   ├── model_summary.txt
│   ├── non_stream.tflite
│   └── tflite_non_stream_model_accuracy.txt
├── quantize_opt_for_size_tflite_stream_state_external
│   ├── model_summary.txt
│   ├── stream_state_external.tflite
│   ├── tflite_stream_state_external_model_accuracy_reset0.txt
│   └── tflite_stream_state_external_model_accuracy_reset1.txt
├── stream_state_internal
│   ├── assets
│   ├── model_summary.txt
│   ├── saved_model.pb
│   └── variables
│       ├── variables.data-00000-of-00002
│       ├── variables.data-00001-of-00002
│       └── variables.index
├── tf
│   ├── model_summary_non_stream.png
│   ├── model_summary_non_stream.txt
│   ├── model_summary_stream_state_external.png
│   ├── model_summary_stream_state_external.txt
│   ├── model_summary_stream_state_internal.png
│   ├── model_summary_stream_state_internal.txt
│   ├── stream_state_external_model_accuracy_sub_set_reset0.txt
│   ├── stream_state_external_model_accuracy_sub_set_reset1.txt
│   ├── tf_non_stream_model_accuracy.txt
│   ├── tf_non_stream_model_sampling_stream_accuracy.txt
│   └── tf_stream_state_internal_model_accuracy_sub_set.txt
├── tflite_non_stream
│   ├── model_summary.txt
│   ├── non_stream.tflite
│   └── tflite_non_stream_model_accuracy.txt
├── tflite_stream_state_external
│   ├── model_summary.txt
│   ├── stream_state_external.tflite
│   ├── tflite_stream_state_external_model_accuracy_reset0.txt
│   └── tflite_stream_state_external_model_accuracy_reset1.txt
└── train
    ├── 0weights_400.data-00000-of-00002
    ├── 0weights_400.data-00001-of-00002
    ├── 0weights_400.index
    ├── ...
    ├── 9027weights_15000.data-00000-of-00002
    ├── 9027weights_15000.data-00001-of-00002
    ├── 9027weights_15000.index
    └── checkpoint
```

**Comment by rybakov** [comment]
Thank you! I also updated final files tree with description.
