### ISSUE TITLE
question on 'Distilling Effective Supervision from Severe Label Noise'(CVPR 2020)

### ISSUE THREAD

**Issue by luochonghai** [google-research/google-research#301]
I meet a problem when reading the source code of Distilling Effective Supervision from Severe Label Noise(IEG). In the paper, the re-weighting coefficients are updated in this way:
![image](https://user-images.githubusercontent.com/22375420/85141951-34371200-b27a-11ea-82df-2e3cd8d1d76e.png)
Then I find the corresponding implementation in https://github.com/google-research/google-research/blob/master/ieg/models/model.py:
![image](https://user-images.githubusercontent.com/22375420/85142232-9f80e400-b27a-11ea-98ef-8a10b8c1d2ca.png)
So **raw_weight =  target - grad_target - init_eps_val**
![image](https://user-images.githubusercontent.com/22375420/85142472-07372f00-b27b-11ea-8d45-a1c10680b653.png)
So target is constant: **target = init_eps_val**
Then we simply get: **raw_weight = -grad_target**, so the updating equation would be written in this way:
![image](https://user-images.githubusercontent.com/22375420/85143441-56ca2a80-b27c-11ea-999a-2f48c4093775.png)

and it doesn't satisfy the updating strategy mentioned in the paper. So is there anything wrong with the implementation of code, or the formula in the paper?

**Comment by zizhaozhang** [comment]
Hi @luochonghai,

Thanks for bringing up the question and detailed explanation. I think your derivation is correct. 

`raw_weight = target - grad_target - init_eps_val := - grad_target. 
`

Previously we were treating 
`raw_weight = raw_weight - init_eps_val` and the following [3 lines](https://github.com/google-research/google-research/blob/master/ieg/models/model.py#L311-L315) as the normalization step as only briefly mentioned in the paper.

The conclusion here is that the implementation is correct and the formula is less precise. Both leads to the same outputs. We will update the paper to reduce confusion.

**Comment by luochonghai** [comment]
Many thx~
