### ISSUE TITLE
I meet Error when run code in the project "pairwise_fairness"

### ISSUE THREAD

**Issue by Fanshaoliu** [google-research/google-research#306]
I had read your paper in AAAI 2020 about fairness metrics, but when I run your code there occurs error about:
`AttributeError: module 'tensorflow' has no attribute 'function'，`
and the first place in traceback is 
```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-c69db21a2d00> in <module>()
      1 # Tensor flow lattice modules.
----> 2 import tensorflow_lattice as tfl
      3 
      4 # Tensorflow constrained optimization modules.
      5 import tensorflow_constrained_optimization as tfco
```

Please take a look, thank you!

**Comment by Aniketks29** [comment]
Try importing tensorflow before importing tensorflow_lattice
![Screenshot (97)](https://user-images.githubusercontent.com/44942350/85902138-ee052400-b820-11ea-826b-52978eed9be7.png)

**Comment by Fanshaoliu** [comment]
Thank you! It works!

**Comment by Aniketks29** [comment]
Glad to help
