### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by YangXh616** [google-research/google-research#31]
saver = tf.train.import_meta_graph(FLAGS.model_ckpt + '.meta')

  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1449, in import_meta_graph
    **kwargs)[0]

  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1463, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)

  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 695, in read_meta_graph_file
    text_format.Merge(file_content.decode("utf-8"), meta_graph_def)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 1: invalid continuation byte

**Comment by MortenHannemose** [comment]
The error is regarding the **unprocessing** code.
I get the same error, when I try to load the uploaded models.
I am using Python 3.6.8, tensorflow 1.13.1.
I get the same error on Windows and Ubuntu.

**Comment by TouqeerAhmad** [comment]
I'm also getting the same error on Ubuntu with the following setup:
Tensorflow: 1.13.1, Python: 3.7.3

**Comment by jonbarron** [comment]
Sorry about this, we're taking a look.

**Comment by laoyangui** [comment]
The problem has been solved on this website: https://github.com/tensorflow/tensorflow/issues/19721

**Comment by YangXh616** [comment]
> 该网站已解决该问题：[tensorflow / tensorflow＃19721](https://github.com/tensorflow/tensorflow/issues/19721)
Still not solved

**Comment by jonbarron** [comment]
Thanks for the link, it looks like our model checkpoints are missing a .checkpoint file. We'll address this as soon as possible, but it's a US holiday this week.

**Comment by YangXh616** [comment]
> Thanks for the link, it looks like our model checkpoints are missing a .checkpoint file. We'll address this as soon as possible, but it's a US holiday this week.

One more question: shot_noise_tensor = graph.get_tensor_by_name('stddev/shot_noise:0')
Read_noise_tensor = graph. Get_tensor_by_name (' stddev/read_noise: 0 ')
It doesn't seem to exist in the original graph.

**Comment by jonbarron** [comment]
Hi, sorry for the delay, this problem has been resolved, just re-download the models linked to in the README. Ping me via email if you continue having issues.
