### ISSUE TITLE
KWS streaming TFLite via CoreML delegate

### ISSUE THREAD

**Issue by entn-at** [google-research/google-research#310]
I'm very interested in the work presented in the KWS streaming project. Do TFLite models converted to streaming mode (internal or external state) also work (in streaming mode) when used via [TF Lite CoreML delegate](https://www.tensorflow.org/lite/performance/coreml_delegate) on iOS devices? In this case, can `mfcc_op` be used on CoreML/iOS, or only `mfcc_tf` (or do speech feature extraction outside of the model)?
@rybakov

**Comment by rybakov** [comment]
Comments about conversion steps:
1 TensoFlow(TF) model can be converted to TF streaming model with external or internal state.
2 TF streaming models with external state can be converted to TFLite and run on mobile devices (benchmarks in streaming and non streaming modes were reported in our [paper](https://arxiv.org/abs/2005.06720)).
3 TF streaming models with internal state can not be converted to TFLite now - this work is still in progress.

Comments about speech feature extractor:
4 mfcc_tf should work everywhere. It is implemented based on DFT and uses only basic ops such as matrix matrix multiplication.
5 mfcc_op is implemented based on FFT. It is a special op in TFLite. This feature extractor can be part of the model (set by preprocess 'raw'; feature_type 'mfcc_op') or it can be outside of the model (set by preprocess 'mfcc';). In both cases it is the same TFLite op and if it works for one case it will work for another too. I never tested it on CoreML/iOS. Please feel free to try it and let me know if you have any problems. If it does not work we can create an issue for TFLite team.

**Comment by entn-at** [comment]
Thanks for the detailed response!

**Comment by rybakov** [comment]
Quick note: mfcc_tf can be slower than mfcc_op because one uses DFT and another FFT. Also mfcc_op is preferable in case if you plan to quantize your model.
