### ISSUE TITLE
The issues about kws_streaming.

### ISSUE THREAD

**Issue by ChuHengLee** [google-research/google-research#312]
Firstly I would like to thank you for providing the source code about keyword spotting.

The issues are following:

1.When I run inference.ipynb, the error occurs. It can not import "_HOTWORD_MODEL_PARAMS", too. It seems that utils_test.py does not declare "Flags" and "_HOTWORD_MODEL_PARAMS".
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
ImportError   Traceback (most recent call last)
ipython-input-66-2f238aecf54f in module
        3 import tensorflow.compat.v1 as tf1
        4 import logging
----> 5 from kws_streaming.models.utils_test import Flags, _HOTWORD_MODEL_PARAMS

ImportError: cannot import name 'Flags' from 'kws_streaming.models.utils_test'
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 

2.How can I know the predicted label after inference? The source code only outputs the index number. There might be 12 classes including "unknown" and "silence".
print(flags.wanted_words) # 10 predefined words: yes,no,up,down,left,right,on,off,stop,go

**Comment by rybakov** [comment]
Thank you for evaluating kws_streaming!

_"1.When I run inference.ipynb, the error occurs."_
Thank you for reporting this issue. ipynb is outdated. The fix will be in couple of days.

_"2.How can I know the predicted label after inference?"_
Please have a look at [check-data](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/check-data.ipynb). It has an example of mapping index_to_label:
{1: '_unknown_',
 5: 'down',
 11: 'go',
 3: 'no',
 7: 'right',
 8: 'on',
 6: 'left',
 2: 'yes',
 9: 'off',
 4: 'up',
 10: 'stop',
 0: '_silence_'}

unknown=1 and silence=0 always.
I will update notebooks with more details and then post another comment here.

**Comment by rybakov** [comment]
I have updated colabs, please run them one by one:

1. [00_check_data](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/00_check_data.ipynb) it shows index_to_label and will prepare data set v2

2. [01_train](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/01_train.ipynb) it will train a model (with small number of iterations, so accuracy will not be high) this step is optional.

3. [02_inference](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/02_inference.ipynb) it will run inference on pre-trained models (I added a remapping from id to word)

Please let me know if you have any questions or issues.

**Comment by ChuHengLee** [comment]
Thank you for updating the files.

The issues are following:
1. In 01.train, FLAGS.data_url should be set to empty string to avoid error.
2. I printed "index_to_label[stream_output_arg]" in streaming mode with external state. And I found that "left" appears in the beginning of inference whatever audio files were used. Why it would not be "unknown"?
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
The ouput example of infering "/kws_streaming/data2/on/fb7c9b3b_nohash_0.wav"
![on_example](https://user-images.githubusercontent.com/44760575/86198151-87b63380-bb89-11ea-8336-a24477109766.png)
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
3. I am interested in detecting multiple keywords in a realistic scenario. Do you have any advice?  

Thanks again!

**Comment by rybakov** [comment]
1 Please update both colab and kws code, so there will be no issues with data_url in colab (setting it to empty string in colab works too).

2 Speech commands data with 10 + 2 categories is a toy data set.
It has: 
training_set_size 22,246
testing_set_size 3,081
validation_set_size 3,093
To be able to classify all other unknown sounds with better accuracy you will need to prepare more negative/"unknown" examples and use larger data sets.
Also [models2_30k.zip](https://storage.googleapis.com/kws_models/models2_30k.zip) which are used in [02_inference.ipynb](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/02_inference.ipynb) are realy toy models with 30K parameters.
These kind of models can be good for microcontrollers with limited cpu and memory.

3.1 If you do not have limitations on model size, I would suggest to look at [models2](https://storage.googleapis.com/kws_models/models2.zip) published in our [paper](https://arxiv.org/abs/2005.06720) and its quantizerd version [models2_q](https://storage.googleapis.com/kws_models/models2_q.zip). These models are well suited for mobile phones: have more parameters with better accuracy. You can also use more accurate non streaming models and run them every 50ms (for example). Some of non streaming models (with stride and pooling) can be converted to streaming mode (it just not implemented in kws, please feel free to convert them and contribute)
3.2 When you run your model in streaming mode you should analyze not only predicted word, but its confidence level too
In the this collab example: [02_inference.zip](https://github.com/google-research/google-research/files/4856123/02_inference.zip), I showed both predicted word and confidence level of predicted word in streaming mode. You can see that with more data in time, confidence level grows and it has highest value in the end of the word. So in addition to checking what is the current word you should also compare its confidence level with a threshold (and check that it is a local maximum). Also detection events should be smoothed: for example trigger word detection if it was detected 5 times in the last 100ms of audio.
I would also suggest to compute more metrics for example streaming false alarm and false reject per hour (in our paper we use accuracy metric only for academic purpose and comparison with other previously published work).
3.3 There can be false positives on short words such as "on". For example "on" can be detected in words "common", "lemon", etc
3.3 Use more data

**Comment by ChuHengLee** [comment]
Thank you for your advice.
