### ISSUE TITLE
mobileBERT multilingual support

### ISSUE THREAD

**Issue by yaysummeriscoming** [google-research/google-research#336]
Very impressed by the performance that mobileBERT delivers, is it possible to get a multi-lingual version please?

**Comment by Elikrag** [comment]
Agree, would love a multi-lingual version.

**Comment by Wikidepia** [comment]
They recently release MobileBERT Multilingual [here](https://tfhub.dev/tensorflow/mobilebert_multi_cased_L-24_H-128_B-512_A-4_F-4_OPT/1)
