### ISSUE TITLE
Running Inference for Unprocess Net on real-world RGB image 

### ISSUE THREAD

**Issue by TouqeerAhmad** [google-research/google-research#34]
Hi, 

Questions regarding denoiser models from paper "Unprocessing Images for Learned Raw Denoising". Can I run the inference for some arbitrary already noisy image (RGB) if I don't have access to noise information (shot and read noises) from metadata?

Specifically in the 'dnd_denoise.py' file, I can see the feed_dict comprised of noisy image, read and shot noise tensors. 

Thanks!

**Comment by jonbarron** [comment]
This model relies very heavily on having metadata for your image. If you can't get it, you could try using the metadata from an image in our unprocessed training data, or from one of the images in the Darmstadt dataset, but all of our experiments suggest that performance will get significantly worse if your metadata is incorrect.

**Comment by timothybrooks** [comment]
Please see the "Evaluation on Different Real Data" section of our README, which explains what inputs are required, and how to attain those inputs:
https://github.com/google-research/google-research/tree/master/unprocessing#evaluation-on-different-real-data

It is possible to calibrate a new camera to attain shot and read noise as a function of ISO, and it is possible to approximate shot and read noise parameters from a single image. However, the models are only for denoising raw Bayer images, so you will not be able to denoise an RGB image directly.

**Comment by TouqeerAhmad** [comment]
Thank you I understand! I think I was thrown off since the results were reported for RGB images as well -- but after reading the paper carefully I figured denoising is still done for Raw bayer pattern and just PSNR is computed by converting both GT and denoised images to RGB space. Thank you for your replies!
