### ISSUE TITLE
[uflow] The code only uses single GPU and causes OOM for batch size == 32

### ISSUE THREAD

**Issue by hzxie** [google-research/google-research#341]
The code only uses single GPU and causes OOM for batch size == 32

**Comment by AustinCStone** [comment]
Hi hzxie,

We had used TPUs to train with batch size 32. We recommend training with batch size 1 on GPU. Although it takes longer to train from scratch (approximately 2.5 days on a V100), we found it converges to the same results as batch size 32 on TPUs.

Thanks.

**Comment by hzxie** [comment]
OK. Got it. I'll try it.
Thank you for your response.
