### ISSUE TITLE
RuntimeError: Error initializing searcher: 

### ISSUE THREAD

**Issue by najafmurtaza** [google-research/google-research#347]
Code:
```
def f(x):
       return np.random.rand(100)

train_data['emb'] = train_data['text'].apply(f)
test_data['emb'] = test_data['text'].apply(f)

dataset = np.array(train_data['emb'].tolist(), dtype=np.float32)
queries = np.array(test_data['emb'].tolist(), dtype=np.float32)
```

Error:
```
normalized_dataset = dataset / np.linalg.norm(dataset, axis=1)[:, np.newaxis]
# configure ScaNN as a tree - asymmetric hash hybrid with reordering
# anisotropic quantization as described in the paper; see README

#  ----- At this line -----

searcher = scann.ScannBuilder(normalized_dataset, 10, "dot_product").tree(
    num_leaves=2000, num_leaves_to_search=100, training_sample_size=250000).score_ah(
    2, anisotropic_quantization_threshold=0.2).reorder(100).create_pybind()
```
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c748bb36181c>", line 6, in <module>
    2, anisotropic_quantization_threshold=0.2).reorder(100).create_pybind()
  File "/home/dev/.local/lib/python3.6/site-packages/scann/scann_ops/py/scann_builder.py", line 203, in create_pybind
    self.training_threads)
  File "/home/dev/.local/lib/python3.6/site-packages/scann/scann_ops/py/scann_ops_pybind.py", line 60, in create_searcher
    scann_pybind.ScannNumpy(db, scann_config, training_threads))
RuntimeError: Error initializing searcher:

**Comment by najafmurtaza** [comment]
The issue is resolved. 
It turns out, searcher expects lots of training(dataset) examples. 
In my case I had only 50 in dataset var.

**Comment by CarolineTong** [comment]
hello, I meet the same problem. How to fix this?

**Comment by CarolineTong** [comment]
hello, I meet the same problem. How to fix this?
