### ISSUE TITLE
build_pip_pkg fails

### ISSUE THREAD

**Issue by Iicolan** [google-research/google-research#358]
Hello:
   I have install bazel 0.21.0, clang 8 and gcc 9. And the step "python configure.py" runs successfully, but when I try step 2: CC=clang-8 bazel build -c opt --copt=-mavx2 --copt=-mfma --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt="-std=c++17" --copt=-fsized-deallocation --copt=-w :build_pip_pkg, it fails with:
ERROR: scann/scann_ops/py/BUILD.bazel:28:1: //scann/scann_ops/py:scann_ops_test: no such attribute 'python_version' in 'py_test' rule
ERROR: py/BUILD.bazel:6:1: Target '//scann/scann_ops/py:scann_ops' contains an error and its package is in error and referenced by '//scann/scann_ops/py:scann'
ERROR: scann_ops/py/BUILD.bazel:6:1: Target '//scann/scann_ops/py:scann_ops_pybind' contains an error and its package is in error and referenced by '//scann/scann_ops/py:scann'
ERROR: /BUILD.bazel:6:1: Target '//scann/scann_ops/py:scann' contains an error and its package is in error and referenced by '//:build_pip_pkg'
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.038s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 21 targets configured)
 Have you ever meet the same problem? can you help me have a look at this problem?

**Comment by dongzhen123** [comment]
Have you solved it? I have trouble in build from source too.

**Comment by Iicolan** [comment]
> Have you solved it? I have trouble in build from source too.
I have solved this problem. I uninstall bazel 0.21.0 and install bazel with the version of 3.4.1. And if it prompts a error in python path, you can try add "--action_env=PYTHON_BIN_PATH=/usr/bin/python3" at the end of step 2.

**Comment by dongzhen123** [comment]
> > Have you solved it? I have trouble in build from source too.
> > I have solved this problem. I uninstall bazel 0.21.0 and install bazel with the version of 3.4.1. And if it prompts a error in python path, you can try add "--action_env=PYTHON_BIN_PATH=/usr/bin/python3" at the end of step 2.

Do you know
which message in the proto should we used to parse  "serialized-partitioner.pb"?  and 
What information  we get from this file?

**Comment by dongzhen123** [comment]
> > Have you solved it? I have trouble in build from source too.
> > I have solved this problem. I uninstall bazel 0.21.0 and install bazel with the version of 3.4.1. And if it prompts a error in python path, you can try add "--action_env=PYTHON_BIN_PATH=/usr/bin/python3" at the end of step 2.

可以加个微信交流下关于scann的吗？
My wechat:   worddz

**Comment by Iicolan** [comment]
> > > Have you solved it? I have trouble in build from source too.
> > > I have solved this problem. I uninstall bazel 0.21.0 and install bazel with the version of 3.4.1. And if it prompts a error in python path, you can try add "--action_env=PYTHON_BIN_PATH=/usr/bin/python3" at the end of step 2.
> 
> 可以加个微信交流下关于scann的吗？
> My wechat: worddz

**Comment by cramraj8** [comment]
How did anyone solve it ?
