### ISSUE TITLE
How to load the .pb file generate from scann?

### ISSUE THREAD

**Issue by dongzhen123** [google-research/google-research#376]
when use "searcher.serialize()",we could get some file,then how to open the .pb file ?

**Comment by ahuizxc** [comment]
# searcher = scann_builder.create_pybind()
# searcher.serialize("./docs/trained_model")
searcher = scann_ops_pybind.load_searcher(normalized_dataset, "./docs/trained_model")

Best Regards!

**Comment by Darateja** [comment]
Give me money please 2000 rupees
