### ISSUE TITLE
[KWS] error in using my own dataset,when training

### ISSUE THREAD

**Issue by xcrpkuss** [google-research/google-research#381]
I want to test the model in another dataset called "mobvoi_hotword_dataset".
And  I changed its file folder like "speech commond", but when train the model and run the sess, it happens an error
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 17: invalid start byte“

![4](https://user-images.githubusercontent.com/56855140/92067704-85fe2b80-edd7-11ea-8c59-202578e7df1d.gif)

I don't know what will be done in the sess,and can't solve it.It's really thank you, if you can give me some suggestions!
I use the data below.

![1](https://user-images.githubusercontent.com/56855140/92067526-20aa3a80-edd7-11ea-82a0-c27eaa972170.png)

**Comment by xcrpkuss** [comment]
![image](https://user-images.githubusercontent.com/56855140/92067907-0ae94500-edd8-11ea-970c-98c6db4eeb64.png)

**Comment by xcrpkuss** [comment]
![image](https://user-images.githubusercontent.com/56855140/92068077-84813300-edd8-11ea-9c40-34ff0b0e1899.png)
Oh,maybe because of the size of wav file?
Thank you1

**Comment by xcrpkuss** [comment]
Oh it's because of the syntax of my wav file, I solve by changing them.
I'm sorry disturbed you.

**Comment by rybakov** [comment]
Hi xcrpkuss, thank you for evaluating kws lib! I did not test kws lib on mobvoi_hotword_dataset and curios to see how it goes, please keep me updated and let me know if you need any help with kws. /Oleg

**Comment by xcrpkuss** [comment]
The project is everything ok in my task.
Previous error is due to the different chunk head of my data.
I change the chunk head and it's running now.
Thank you
