### ISSUE TITLE
[Scann] Building from source shows error (undefined symbol: _Py_ZeroStruct)

### ISSUE THREAD

**Issue by YJYJLee** [google-research/google-research#402]
I followed the instructions in README to build Scann from source.
- python configure.py
- CC=clang-8 bazel build -c opt --copt=-mavx2 --copt=-mfma --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt="-std=c++17" --copt=-fsized-deallocation --copt=-w :build_pip_pkg
- ./bazel-bin/build_pip_pkg

All three commands passed without any errors.
But after installation, when I'm trying to import scann, it shows the following error
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/scann/__init__.py", line 1, in <module>
    from scann.scann_ops.py.scann_builder import ScannBuilder
  File "/usr/local/lib/python3.6/dist-packages/scann/scann_ops/py/scann_builder.py", line 18, in <module>
    from scann.scann_ops.py import scann_ops_pybind
  File "/usr/local/lib/python3.6/dist-packages/scann/scann_ops/py/scann_ops_pybind.py", line 30, in <module>
    import scann_pybind
ImportError: /usr/local/lib/python3.6/dist-packages/scann/scann_ops/cc/python/scann_pybind.so: undefined symbol: _Py_ZeroStruct**

Any idea on this error?

**Comment by eugeneyan** [comment]
I have a similar but different error.

```>>> import scann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/__init__.py", line 3, in <module>
    from scann.scann_ops.py import scann_ops_pybind
  File "/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/py/scann_ops_pybind.py", line 30, in <module>
    import scann_pybind
ImportError: dlopen(/Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so
  Expected in: flat namespace
 in /Users/eugeneya/projects/Cobar/src/Cobar/google-research/scann/.venv/lib/python3.7/site-packages/scann/scann_ops/cc/python/scann_pybind.so```

Were you able to resolve this eventually? I've tried on both Python 3.7.9 and Python 3.8.6 and both lead to the same error.

**Comment by miniuig** [comment]
I have the same problem. Have you solved it?

**Comment by eugeneyan** [comment]
Yes, I was able to install it successfully and wrote about it [here](https://eugeneyan.com/writing/how-to-install-scann-on-mac/).

**Comment by miniuig** [comment]
> I followed the instructions in README to build Scann from source.
> 
> * python configure.py
> * CC=clang-8 bazel build -c opt --copt=-mavx2 --copt=-mfma --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --cxxopt="-std=c++17" --copt=-fsized-deallocation --copt=-w :build_pip_pkg
> * ./bazel-bin/build_pip_pkg
> 
> All three commands passed without any errors.
> But after installation, when I'm trying to import scann, it shows the following error
> **Traceback (most recent call last): File "", line 1, in File "/usr/local/lib/python3.6/dist-packages/scann/**init**.py", line 1, in from scann.scann_ops.py.scann_builder import ScannBuilder File "/usr/local/lib/python3.6/dist-packages/scann/scann_ops/py/scann_builder.py", line 18, in from scann.scann_ops.py import scann_ops_pybind File "/usr/local/lib/python3.6/dist-packages/scann/scann_ops/py/scann_ops_pybind.py", line 30, in import scann_pybind ImportError: /usr/local/lib/python3.6/dist-packages/scann/scann_ops/cc/python/scann_pybind.so: undefined symbol: _Py_ZeroStruct**
> 
> Any idea on this error?

Have you solved it?
