### ISSUE TITLE
[KWS] input_audio shape in stream model

### ISSUE THREAD

**Issue by LeeYongHyeok** [google-research/google-research#416]
Hi, I have question about input_audio layer shape in stream model.
In my case, I got the `512 length` audio packet and feed this data to kws stream model.
So I set the train arguments as input audio properties (`--sample_rate 16000`, `--window_size_ms 32.0`, `--window_stride_ms 16.0`).
Each window and stride size is 512 and 256, So I expect 512 dim. input_audio layer.
But I find the my converted model input_audio shape is `[1, 256]`.
Why?

**Comment by rybakov** [comment]
@LeeYongHyeok the shape of input data in streaming mode depends on "preprocess" flag.
By default preprocess=raw, I guess that is what you use in your example.

**For the case when preprocess=raw**
In this case model has [speech feature extractor](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/speech_features.py) with [data framing](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/data_frame.py) and neural network parts - so it is end to end model.
Speech feature extractor layer has several steps: 
1 data framing which will automatically create audio frames.
2 convert audio frames to spectrum features mfcc.

With your parameters
window_size_ms  = 32.0ms
window_stride_ms  = 16.0ms
audio frames will looks like this:

        32.ms(frm_0)
<--------------------->
                       32ms (frm_1)
                <--------------------->
                               32ms (frm_2)
                              <--------------------->

Let assume that model already processed frm_0, now we need to form frm_1 in [data_frame](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/data_frame.py). To generate frm_1 we need prev_0 and next_1 shown below:
        32.ms(frm_0)      
<--------------------->
                  prev_0    next_1
               <---------><--------->
                       32ms (frm_1)
               <--------------------->

Length of next_1 = 16ms is 256 samples - this is the input shape in streaming mode.
We get prev_0 from frm_0, by taking last 256 samples and then concatenate is with next_1 and get frm_1 = concat(prev_0, next_1).
Now we can repeat this process for next iteration.
[data_frame](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/data_frame.py) keeps the state of the previous frame and manages framing automatically for you, so you just need to feed the new update data with size 256 samples.


**For the case when preprocess=mfcc or preprocess=micro**
Model will receive mfcc features as input, so the input shape in streaming mode will be dct_num_features as shown in [link] (https://github.com/google-research/google-research/blob/master/kws_streaming/layers/modes.py#L69)
In this case framing and speech feature extraction will happen outside of the model and you will need to manage it by yourself.

Thank you for evaluating kws lib! please let me know if you have more questions.

**Comment by LeeYongHyeok** [comment]
@rybakov Thanks for your kindly answer.
Let assume that i got the audio data as `512 dim. 1 frame` from recording device, and then i stack the audio data in recording buffer and feed them to KWS model without any overlap data?

**Comment by rybakov** [comment]
Yes, you should read the audio frames from recording device, stack them in a recording buffer. 
Then read 256 samples (with no overlaps) from recording buffer and feed it into model, then repeat it until recording buffer has no data left.

Please have a look at [colab example](https://github.com/google-research/google-research/blob/master/kws_streaming/colab/02_inference.ipynb) in this example _input_data_ has the whole sequence of audio samples and during streaming we feed _stream_update_ into the model with no overlap. You can think about _input_data_  as your recording buffer.

**Comment by LeeYongHyeok** [comment]
@rybakov Thank you so much. have a nice day :)

**Comment by rybakov** [comment]
If you plan to run your model on mobile phone, I would suggest to use:
 --feature_type 'mfcc_op'
as it is shown in [kws_experiments_q](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_q.md)
It will reduce model size significantly and will allow you to quantize the model and get 2x speed up.
