### ISSUE TITLE
[POEM] Pretrained model? How to generate TFRecords?

### ISSUE THREAD

**Issue by emredog** [google-research/google-research#421]
Hello!

Thanks for the great work and sharing it publicly! Definitely one of the best papers I've read this summer.

I need help running it though:
1. AFAIK, there are no pre-trained models shared, are there?
2. Looking at the [poem](https://github.com/google-research/google-research/tree/master/poem) code, we have the training code, and it uses a sample tfrecords file, namely `poem/testdata/tfe-2.tfrecords`. Is there a full version of this file? Or is there code to generate a full version? 

Thanks in advance!

**Comment by jenjsun** [comment]
Hello and thanks for your interest! 
1. There are no pre-trained models shared at the moment.
2. We added code to generate the tfrecords file from a csv file to /tools/gen_train_tfrecords.py. We are still working on releasing the code to generate the csv but feel free to use your own csv as input!

Let us know if there is anything else!

**Comment by emredog** [comment]
Thanks for the info Jennifer!

**Comment by jenjsun** [comment]
No problem! Ting (co-author) added the script. Feel free to close the issue if this is good for now - and feel free to contact us with any other questions!
