### ISSUE TITLE
[Closed Book QA w/ T5] Report performance of other checkpoints ?

### ISSUE THREAD

**Issue by ratthachat** [google-research/google-research#425]
Thanks for all the great works on [Closed Book QA w/ T5](https://github.com/google-research/google-research/tree/master/t5_closed_book_qa)  !!

As the paper illustrated only performances of XXL-SSM models, 
I have two questions on other checkpoints:

1) Could you please report the test performances on all datasets of other released checkpoints ?? 
In particular,
T5.1.1-small + SSM + Natural Questions (train)
T5.1.1-XL + SSM + Natural Questions (train)

2) Since T5-XL & XXL are too big to train in Colab-pro (high-ram mode), so
is it possible to release T5.1.1-large + SSM + Natural Questions (train) checkpoint ?

(EDIT : I humbly tag @adarob as the topic author)

**Comment by adarob** [comment]
I will try to get to it today!

**Comment by ratthachat** [comment]
Thanks Adam @adarob !

Aside from that, I would also love to try loading these T5.1.1 checkpoints into huggingface library, but it's not possible without knowing exact different between original T5 and T5.1.1 .  I could not find any source code of T5.1.1 , is it possible to provide the link to the source?

**Comment by adarob** [comment]
Sorry for the delay, but I will make sure to do it early next week. @craffel will be your best resource for T5.1.1 over in https://github.com/huggingface/transformers/issues/6285#issuecomment-714838398
