### ISSUE TITLE
[Controlled Web Noise Labels] Many of the Dataset urls are broken

### ISSUE THREAD

**Issue by cdjkim** [google-research/google-research#429]
Hi, leaving an issue here because the author's statement on the Controlled Noisy Web Label page states, "Please contact us via controlled-noisy-labels@googlegroups.com, if you have any questions or difficulty in reproducing our results on this dataset." However, the googlegroups does not exist. 

When downloading the images through the given URLs, too many of the image URLs are broken. In order to perform honest comparisons for progress in the field, could the authors propose an alternative solution? 

Thanks

**Comment by cdjkim** [comment]
Solved by author response via email

**Comment by zylprivate** [comment]
> 通过作者通过电子邮件回复解决

Could you give me  the author solution ? Thank you very much !
