### ISSUE TITLE
[Performer] prefix-sum computations is the main reason for speedup, but what is the reason for accuracy-up?

### ISSUE THREAD

**Issue by guotong1988** [google-research/google-research#438]
Based on my understanding only.
Thank you, thank you and thank you.

**Comment by kchoro** [comment]
Thank you for the comment ! So accuracy gains can come from other (than softmax) kernels used in the attention mechanism (FAVOR provides a framework for generalized attention with regular softmax-based one only as a special instantiation and gives linear space & time complexity also for the generalized model). For instance, we observed that in practice Performer-ReLU leveraging kernels with ReLU nonlinearities works very well (see: https://arxiv.org/abs/2009.14794).

**Comment by guotong1988** [comment]
Thank you. I will try to understand.
