### ISSUE TITLE
Could someone provide the supplementary material of this paper ? Unsupervised Monocular Depth Learning in Dynamic Scenes

### ISSUE THREAD

**Issue by whyygug** [google-research/google-research#453]
I downloaded this paper but can't find the supplementary material.
Unsupervised Monocular Depth Learning in Dynamic Scenes [https://arxiv.org/abs/2010.16404](url)
Could someone provide it? Thanks !

**Comment by jessedaniels** [comment]
There is a supplementary materials section of this version of the paper: 
https://storage.googleapis.com/pub-tools-public-publication-data/pdf/662284996d9111bef7ba49285e71ce62a5f2ecbd.pdf
Although I'm not sure it contains everything they reference in the arxiv version.

**Comment by whyygug** [comment]
@jessedaniels Thank you ！

**Comment by uniqueness** [comment]
See "Ancillary files" of that arxiv page.

**Comment by whyygug** [comment]
@uniqueness Thank you.  I followed your instructions and found the supplementary material, as well as some videos.
