### ISSUE TITLE
[POEM] More Info. in Readme

### ISSUE THREAD

**Issue by Deepanshu-beep** [google-research/google-research#475]
Kindly Update the readme of POEM repo, with all the steps to download dataset, Train the model and then how to Evaluate and reproduce the same results as mentioned in the paper.

**Comment by zp2388** [comment]
I also want to get records of the above mention...

**Comment by jenjsun** [comment]
Hello! We have provided a data processing script on our website here: https://sites.google.com/view/
pr-vipe
