### ISSUE TITLE
[KWS] update guide for stream models

### ISSUE THREAD

**Issue by LeeYongHyeok** [google-research/google-research#476]
Can you update example guide for new models in stream mode?
I am now confused about which of the many models are streamable and which are not.
Thanks,

**Comment by rybakov** [comment]
Thank you for your feedback!
I updated [description](https://github.com/google-research/google-research/tree/master/kws_streaming) and added an example of [model streaming with stride/pool](https://github.com/google-research/google-research/blob/master/kws_streaming/models/models_test.py). Please let me know if you have any questions.

**Comment by LeeYongHyeok** [comment]
@rybakov 
Thanks for your kind comment!
