### ISSUE TITLE
Data for "smith"

### ISSUE THREAD

**Issue by mle-els** [google-research/google-research#516]
Since Gwikimatch is not available yet, how should I prepare the data to train and test "smith"? Could someone please provide guidance on where to fetch the data or what format the program expects so that I could construct my own data? Thank you very much!

**Comment by gittykhirbat** [comment]
In the same boat. Watching this space.

**Comment by Njust-taoye** [comment]
where is space

**Comment by yangliuy** [comment]
Thank you for your interesting on the SMITH model and Gwikimatch data! I have pushed the data to https://github.com/google-research/google-research/tree/master/gwikimatch. Please check this url for the latest version of data sets.

**Comment by mle-els** [comment]
Thanks, I can download the dataset now!
