### ISSUE TITLE
[POEM]No Negative Samples?

### ISSUE THREAD

**Issue by horsetif** [google-research/google-research#519]
Hi, I am trying to train your network(POEM). But I found that using tools/gen_train_tfrecords.py did not save any negative pairs. And in train_base.py, the contents of "anchor_keypoints" and "match_keypoints" in triplet_loss are exactly the same (I found sum(anchor_keypoints-match_keypoints) == 0).
https://github.com/google-research/google-research/blob/master/poem/train_base.py#L601

 Since there is no evaluation script, it is currently impossible to judge whether the training is correct. So where is "Online Mining" method reflected in the paper? 
Looking forward to your reply.

**Comment by horsetif** [comment]
https://github.com/google-research/google-research/blob/master/poem/tools/gen_train_tfrecords.py#L36
"d. In practice, we include all possible pairs in our training tables. For
   example, for one pose in the Human3.6M dataset (which has 4 views C{0..3}),
   we include all 12 pairs in the CSV, i.e., (C0, C1), (C0, C2), (C0, C3), (C1,
   C0), (C1, C2), (C1, C3), (C2, C0), (C2, C1), (C2, C3), (C3, C0), (C3, C1),
   and (C3, C2)."
If this represents the pose of a single frame, the 3D joint points corresponding to all 12 situations in the current frame are exactly the same. (My current train situation)
If it represents a pose sequence, then there will be very complicated possibilities. I want to know your data package method...

**Comment by jenjsun** [comment]
Hi! Thanks for your interest. You can look at compute_keypoint_triplet_loss for the code which does online negative mining (which means that the negatives are found in the batch): https://github.com/google-research/google-research/blob/da2852b846559efc3f7cff87931268b7edb9730f/poem/core/loss_utils.py#L338. The negatives are the 3D poses in the batch that are different from the anchor, and is computed by the function "compute_negative_indicator_matrix".

We also added a data processing script to our website here: https://sites.google.com/view/pr-vipe and click on "data processing script"

**Comment by horsetif** [comment]
hi, I am glad to receive your reply soon. Thank you very much for explaining this problem to me, I have understood it.(it seems no problem in your training and package code).
I have another question:
The output of the code seems to contain three parts: "embedding mean", "embedding variance", "embedding samples" (20 by default in the code). So in the test application stage, If I input 2D keypoints, which is the output really used for evaluation? Is it just to use "embedding mean" as the real output of the evaluation(like quantitative evaluation in other datasets, retrival, video alignment in paper)? I don't find an explanation in the paper.
Looking forward to your reply.

**Comment by jenjsun** [comment]
In our evaluation, we used the samples (20 samples based on the embedding mean and variance). You can use the embedding mean as well (which is less expensive than using 20 samples, but do not contain variance information).

**Comment by horsetif** [comment]
> In our evaluation, we used the samples (20 samples based on the embedding mean and variance). You can use the embedding mean as well (which is less expensive than using 20 samples, but do not contain variance information).

Thx for your reply. Great job.
