### ISSUE TITLE
How can I use ScaNN with Hamming-Distance?

### ISSUE THREAD

**Issue by tim-hilt** [google-research/google-research#528]
I see the Hamming-distance named on multiple locations in the code, however not in the README or the `algorithms.md`.

Is there some way already to use the Hamming-distance with ScaNN? If so, how would i do that?

**Comment by sammymax** [comment]
No, ScaNN doesn't support hamming distance.

**Comment by tim-hilt** [comment]
This is unfortunate, but answers my question.

Thanks for the response!
