### ISSUE TITLE
How to save ScaNN trained model?

### ISSUE THREAD

**Issue by Audida** [google-research/google-research#529]
I can't find how to save trained model.
I've seen TensorFlow recommenders have scann integrated in their models, and as such have similar saving process like:
```
scann = tfrs.layers.factorized_top_k.ScaNN(model.user_model, num_reordering_candidates=1000)

...
  scann.save(
    path,
    options=tf.saved_model.SaveOptions(namespace_whitelist=["Scann"])
  )
```
Any help will be appreciated.

**Comment by ahuizxc** [comment]
I think if you are using tensorflow, you should call tf.saver.save() to save the session.

> I can't find how to save trained model.
> I've seen TensorFlow recommenders have scann integrated in their models, and as such have similar saving process like:
> 
> ```
> scann = tfrs.layers.factorized_top_k.ScaNN(model.user_model, num_reordering_candidates=1000)
> 
> ...
>   scann.save(
>     path,
>     options=tf.saved_model.SaveOptions(namespace_whitelist=["Scann"])
>   )
> ```
> 
> Any help will be appreciated.

I think if you are using tensorflow, you should call tf.saver.save() to save the session.
