### ISSUE TITLE
kws_stream: failed to retrain DNN model

### ISSUE THREAD

**Issue by wangtz** [google-research/google-research#532]
Steps to reproduce:
Follow the instruction in https://github.com/google-research/google-research/tree/master/kws_streaming to download data and model

Re-train dnn model from scratch on data set V1 and run evaluation:
python -m kws_streaming.train.model_train_eval \
--data_url '' \
--data_dir ./data1/ \
--train_dir ./models1/dnn_1/ \
--mel_upper_edge_hertz 7000 \
--how_many_training_steps 100,100,100 \
--learning_rate 0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 40 \
--dct_num_features 20 \
--resample 0.15 \
--alsologtostderr \
--train 1 \
dnn \
--units1 '64,128' \
--act1 "'relu','relu'" \
--pool_size 2 \
--strides 2 \
--dropout1 0.1 \
--units2 '128,256' \
--act2 "'linear','relu'"

Failure:

  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/platform/
app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 300, in 
run
    _run_main(main, args)
  File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 251, in 
_run_main
    sys.exit(main(argv))
  File "/home/wangtz/google-research/kws_streaming/train/model_train_eval.
py", line 249, in main
    test.tf_stream_state_internal_model_accuracy(flags, folder_name)
  File "/home/wangtz/google-research/kws_streaming/train/test.py", line 34
0, in tf_stream_state_internal_model_accuracy
    flags, model_stream, test_fingerprints)
  File "/home/wangtz/google-research/kws_streaming/train/test.py", line 71
, in run_stream_inference_classification
    stream_step_size = flags.data_shape[0]
AttributeError: 'Namespace' object has no attribute 'data_shape'

**Comment by wangtz** [comment]
@rybakov

**Comment by ybNo1** [comment]
I just replace the bug line and it works :
`# stream_step_size = flags.data_shape[0]
stream_step_size = flags.window_stride_samples * flags.data_stride` @wangtz

**Comment by rybakov** [comment]
Thank you for reporting it! @ybNo1, the replace you suggest will fix the issues.
There was a refactor for internal use case in testing utils and it was not reflected here.
@wangtz the fix is submitted, please pull the latest version and let me know if you have any issues with it.

**Comment by wangtz** [comment]
Thanks @rybakov and @ybNo1  It works now :-)
