### ISSUE TITLE
Difference between code and paper in Meta Pseudo Label

### ISSUE THREAD

**Issue by humandream1** [google-research/google-research#536]
In the paper(https://arxiv.org/abs/2003.10580, page 15), h is calculated by inner product -
![스크린샷, 2021-01-21 14-13-48](https://user-images.githubusercontent.com/30650335/105283030-f8d73a00-5bf2-11eb-8990-640e286b9d45.png)
or cosine similarity between two gradients. 

But in the repository(https://github.com/google-research/google-research/blob/master/meta_pseudo_labels/training_utils.py), h seems to be calculated by some sort of Taylor expansion - 
CE(y_l, S(x_l, \thtea^(t+1)) - CE(y_l, S(x_l, \thtea^(t)).

Which is right? Is one of them wrong or out of date? If not, do authors using the Taylor expansion in CIFAR and using the inner product in ImageNet?

**Comment by OutstanderWang** [comment]
@humandream1  Hi, I have the same question about the scalar h.
Besides the computation of h, I also find that the code uses the soft label, while the paper claims that MPL samples hard pseudo labels from the teacher's output distribution.
https://github.com/google-research/google-research/blob/6a6c881cbce5532bc9661a56476b4f0b97c529ad/meta_pseudo_labels/training_utils.py#L409
![image](https://user-images.githubusercontent.com/7700200/105326379-a6087d00-5c08-11eb-86a6-54ffa650a062.png)

Could @hyhieu help make some explanations?

**Comment by hyhieu** [comment]
### Computation of `h`

`h` is computed using Taylor expansion **to approximate the dot product formula described in the paper**.

The first-order Taylor approximation computes `f(x+h) - f(x) = h^T * grad_f(x)`.

To see why this is the case, please note that `cross_entropy['s_on_l_old']` is `S(x_l; \theta_S^{(t-1)})` in the paper and `cross_entropy['s_on_l_new']` is `S(x_l; \theta_S^{(t)})` in the paper. The difference between these two `theta`s is precisely `grad_S(x_u; \theta_S^{(t-1)})` (or a centralized version derived from moving averages of past gradients).

### Using _hard_ or _soft_ labels

**Comment by humandream1** [comment]
Thank you for your reply. It will be helpful if the content of the paper is updated as well. 

![image](https://user-images.githubusercontent.com/30650335/105439522-5b3e4200-5ca8-11eb-8ba7-137585fecf93.png)
If h is directly approximated from this formula, I presume that appendix A is not necessary anymore.

**Comment by humandream1** [comment]
Thank you for your reply. It will be helpful if the content of the paper is updated as well.
