### ISSUE TITLE
Question about meta pseudo label gradient equation

### ISSUE THREAD

**Issue by DHdroid** [google-research/google-research#537]
Hello, I have two questions about equation 10 of appendix A in your paper.
![image](https://user-images.githubusercontent.com/43927732/105324082-4614d500-5c0e-11eb-8a69-8fd0d5a4f1a4.png)

First, is S(x_u ; theta_T) the correct notation? Based on the content of the research paper and the equations in appendix B, I believe that S(x_u ; theta_T) should be T(x_u ; theta_T). If I am incorrect, would you mind providing me with an explanation as to why the student is using the teacher's weights?
Secondly, I am having difficulty understanding how the variation of the log-gradient trick in the REINFORCE algorithm is applied to equation 10. Would you mind explaining how this log-gradient trick is used?

Thank you for your time and an impressive paper!

**Comment by hyhieu** [comment]
Thank you for your interest in the paper.

First, the `S(x_u, \theta_T)` should be `T(x_u, \theta_T)`. This is a typo, and we will fix it in our next revision. Thank you for spotting the bug.

Second, the log-gradient trick in the REINFORCE algorithm is applied to go from the first line in your screenshot to the second line. Applying the log-gradient trick moves the `\partial / \partial_T` from outside the expectation to inside the expectation, and creates the new term `\partial / partial \theta_T log{...}`

**Comment by DHdroid** [comment]
Thank you for the kind response! 😄
