### ISSUE TITLE
[meta pseudo labels] Difference between the hyperparameter of the code and the hyperparameter of the paper

### ISSUE THREAD

**Issue by kekmodel** [google-research/google-research#540]
`Pseudo label threshold`, `UDA factor`, `UDA temperature`, `batch size for the UDA unlabeled objective`, ...
Which is the best result?

**Comment by hyhieu** [comment]
The code is more up-to-date. The difference in hparams is due to the difference between the environments between our internal experiments and the Cloud machines that we tested the open-sourced code on.
