### ISSUE TITLE
How to predict future values thru TFT

### ISSUE THREAD

**Issue by ashi-k** [google-research/google-research#545]
In tft prediction, how can we forecast Target feature value for future timestamps? tft.predict() method uses previous  num_encoder_steps timestamps to predict values (total_time_steps - num_encoder_steps). But, we're feeding these predicted values as input to tft model. 
For E.g.: In volatility model, 
total_time_steps = 252 + 5
num_encoder_steps = 252
So, when I feed 300 records, then after prediction, Target dataframe contains only 295 records and last 5 Input target values are in the prediction columns (t0, t1, t2, t3, t4). Predicted values are exactly same as that of Input target values. 
How can we predict values for future timestamps?
I also tried by adding a dummy row (target column/observed inputs/known inputs = 0 with future timestamp) as the last record in test data but TFT prediction model is just copy paste Input test data as predicted output values.

I don't know if I am missing something.

**Comment by ashi-k** [comment]
My mistake, i was looking at wrong place.

**Comment by dhsusf** [comment]
Hi, I’ve been confused about this as well. What solution did you find?

**Comment by ashishKAgg** [comment]
> Hi, I’ve been confused about this as well. What solution did you find?

Issue is script_train_fixed_params.py doesn't print/save predicted values and displays only Mean loss value on terminal. To check  predicted values, print/save p90_forecast variable which is populating at following script.
https://github.com/google-research/google-research/blob/master/tft/script_train_fixed_params.py#L157
You can also refer following script which you can use after Model training. It loads trained model and save predicted values in  outputs/saved_models/<your exp>/targets/test_predictions.csv file.
https://github.com/ashishKAgg/tft/blob/master/script_load_predict.py
