### ISSUE TITLE
[POEM] train on entire dataset

### ISSUE THREAD

**Issue by snitchjinx** [google-research/google-research#553]
Hello! Thanks for sharing this work!

I could train on the sampled test data and have successfully produced the training dataset (100 tfrecord files). would you also suggest the proper modification in the `train.py` such that I could train on the full dataset?
(sorry for this "green-hand" question. I'm really new to TensorFlow)

Thank you for your consideration!

**Comment by jenjsun** [comment]
Hello and thanks for your interest! You can run training like this on the full data:

python3 -m poem.train \
  --alsologtostderr \
  --input_table="${TRAIN_INPUT}" \
  --train_log_dir="${TRAIN_DIR}" \
  --batch_size=256 \
  --num_steps=5000000 \
  --input_shuffle_buffer_size=1000000 \
  --input_keypoint_profile_name_2d="LEGACY_2DH36M13" \
  --summarize_percentiles=false \
  --log_every_n_steps=1000  
  
Feel free to change the number of steps, batch size, and learning rate as well. (5 million steps may take a while, so can try 1 million steps first.)

**Comment by snitchjinx** [comment]
Thank you very much for the instructions! It trains very fine now.

**Comment by mlevy2525** [comment]
When you train do you pass all 100 shards in as separate tables. When I do this I run out of memory. How do you handle all of the memory?
