### ISSUE TITLE
[slot_attention] Effective resolution of the input to SlotAttention module

### ISSUE THREAD

**Issue by vadimkantorov** [google-research/google-research#555]
@tkipf Do I understand correctly that it's 128x128 as stated in https://github.com/google-research/google-research/blob/master/slot_attention/object_discovery/train.py#L78 (and the convolutional encoder seems to have stride=1 and padding="same")?

The image in the repo induces to think that it's 8x8, but 8x8 seems to be the resolution only [after slots broadcasting](https://github.com/google-research/google-research/blob/master/slot_attention/model.py#L195):
![](https://github.com/google-research/google-research/raw/master/slot_attention/slot_attention.png)

How important was this high resolution for relatively simple CLEVR-like images? Would it work if there was more subsampling in the network and e.g. the input resolution to the slot attention was 7x7 or 14x14 (like you would get out of resnet18 with effecive stride=8)

Thanks!

**Comment by tkipf** [comment]
Great question! We indeed use no strides in the encoder, so the encoded feature map is still 128x128 in size. Using some strides in the encoder generally works well, but downsampling too harshly tends to reduce performance (i.e. result quality) in my experience (7x7 might potentially be too coarse), at least for a very shallow/naive CNN. I suspect that a ResNet would still work well, though, despite the larger strides.

The illustration in the paper is just meant as an illustration of the idea, hence the 8x8 grid is only meant to show that these are encoded feature maps.

And you are right in that the decoder starts with spatial broadcasting to a 8x8 grid, followed by several (de-)conv layers with strides > 1 to get back to 128x128 resolution.
