### ISSUE TITLE
How the postprocessing in object detection works?

### ISSUE THREAD

**Issue by mariya12290** [google-research/google-research#577]
Hello all,

Thank you for your wonderful work on Tensorflow 3D for lidar point cloud. 

I have a question regarding post processing in [object detection post processing](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/postprocessor.py). 

what is the input shape to the postprocessing? I mean, for an example, usually we get [x,y,z,h,w,l,r] in kitti data set as a output of the model. is input to the postprocessing same as the kitti  based object detection model?

For an example
Could anyone help me to understand?

**Comment by afathi3** [comment]
@mariya12290 

Hi,

I will make sure that we will expand the function docstr to make this more clear.
The first argument that the post [postprocess function](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/postprocessor.py#L92) receives is a dictionary. This dictionary contains standard keys (the key names are defined in [standard_fields.py](https://github.com/google-research/google-research/blob/master/tf3d/standard_fields.py#L260-L276)) for object length, height, width, center, rotation matrix, and score.
length, height, width are [N, 1] tensors
center is a [N, 3] tensor
rotation matrix is a [N, 3, 3] tensor
and score is a [N, C] tensor where C is the number of classes

**Comment by mariya12290** [comment]
@afathi3 
Thanks you so much for the quick response. 

I think I got it partially. I will check it once again. If I have doubt, I will ask, or else I will close the issue in a day.

**Comment by mariya12290** [comment]
@afathi3

Hi,

I have few questions in using your post processing work in my master thesis. I am using voxelnet for object detection and I wrote the code for pre-processing(voxelization) in tensorflow 2.4. Now I need to do post processing 3D NMS instead of using the 2D NMS used in the original network.  

Currenlty I have output of model(Faster RPN )as below:

Bounding Box (None,7)   #using for binary classification
Predicted scores (None,)   #object score       

Now I need to apply 3D NMS for the output of the Faster RPN. How can I utilize your work? I am getting the output in kitti format(X,Y,Z,L,W,H,raw_Z) lidar co-ordinate system. 

Could you please guide me with this probelm?

**Comment by Manueljohnson063** [comment]
@afathi3 @mariya12290 Guys i am new to this ,does it require only point clouds,label,caliberation as data or it is incorporated with images? please help

**Comment by mariya12290** [comment]
@Manueljohnson063  

Hi,

Please give some respect to @afathi3 He is the author of this repo.   

To know what it needs just clone the repo and run it with the data and also check the documentation to know how to use this repo. 

Hope you got my point.

**Comment by Manueljohnson063** [comment]
@mariya12290 Could you please explain what is the meaning of respect!LOL

**Comment by afathi3** [comment]
@mariya12290 
I think [this function](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/box_ops.py#L122) is closest to what you are looking for.
The only thing is that you need to turn your Z_raw into a rotation matrix.
You can do sth like:
c = np.cos(angle)
s = np.sin(angle)
rot_z = np.array([[c, -s, 0], [s, c, 0], [0, 0, 1]])

But also, you need to make sure you move everything into world coordinate (in Kitti everything is in camera coordinate)

**Comment by afathi3** [comment]
@Manueljohnson063 

The pipeline needs point clouds and labels. Currently it doesn't use image data (that is an interesting feature that could be added in the future).

**Comment by Manueljohnson063** [comment]
@afathi3  Thanks for your replay.Some of the repo when i look they are trying to fuse the image data with cloud at some point ,any way thankz for your support once again :)

**Comment by mariya12290** [comment]
@afathi3  Thank you so much. I will check with that.

**Comment by mariya12290** [comment]
@afathi3  Hey,

I checked that function. Since I need to build the graph to use in C++ at the end of my thesis. I can not use [this function](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/box_ops.py#L122l). It is too big implementation and mostly written using numpy. If I start implementing it now in tensorflow, It takes atleast 2 months for me to get the perfect 3D NMS after doing lots of debugging . 

My current situation:

I have implemented preprocessing in tensorflow and have graphs of pre-processing, model, processing on predictions. Now I need to implement [3D NMS](https://github.com/qianguih/voxelnet/blob/b74823daa328fc2fa99452bf79793e1f3c32c72a/model/model.py#L294) to get the max of one bounding box per object in a very short time at the end [till here ](https://github.com/qianguih/voxelnet/blob/b74823daa328fc2fa99452bf79793e1f3c32c72a/model/model.py#L312) to get the graph as well. 

Could you please help me with a simple solution? since you have been studying for a long time, you will have better idea.

If get any hints or suggestions are also fine.  I will implement code my self. 

Thanks in advance

**Comment by mariya12290** [comment]
@Manueljohnson063  Dude you can laugh, I am running out of my time.

**Comment by Manueljohnson063** [comment]
Haha,I had done in detecting single object using voxelnet in my google colab if you want i will share it.

**Comment by mariya12290** [comment]
@Manueljohnson063 

Thank you so much for your generosity.  My task is to detect pedestrain and cyclist. So I trained the model and I got around 48% AP for pedestrian and cyclist. Now I need to get the model as a graph to use on hardware. But my supervisor told me to implement 3D NMS instead of 2D. 
So I have been looking for papers on 3D NMS or Code in github. But I could not able to find a one. 

That"s why I thought of asking @afathi3 . 

When I look into TF3D NMS, they also used 2D NMS in the backend. 

Do you have any Idea regarding 3D NSM or atleast papers to study and implement?

**Comment by mariya12290** [comment]
@afathi3 

Hey

Could you please explain what is the reason for doing the NMS in 2d instead of 3D directly?. And also I have been searching for papers regarding 3D NMS, I have not found one. 

Is there any specific reason for the 2D NMS like computation time or memory consumption, any others ?

**Comment by Manueljohnson063** [comment]
@mariya12290 Dont worry bro let me ask to my friends....i am also a student in bits pilani

**Comment by Manueljohnson063** [comment]
@mariya12290 bro one of my friend send me a paper regaeding the ,could you please share your mail id i will sent it to u!!

**Comment by mariya12290** [comment]
@Manueljohnson063 

Thank you so much. Here is mail ID mariya@rhrk.uni-kl.de

**Comment by mariya12290** [comment]
@Manueljohnson063 

Hey bro,

I have some questions regarding voxelnet. How do you get the inference to run in C++? and  How one can use preprocessing part in C++ (Voxelization) Since it is implemented in numpy and it involves lots of linear algebra. 

Is the pre-processing part included in the graph itself, just like feeding the point clouds and call the needed operation to get the feature, coordinate tensor as a input the main model graph?

Can you please ?
