### ISSUE TITLE
Release CuBERT Finetune Code?

### ISSUE THREAD

**Issue by DNGros** [google-research/google-research#582]
Thanks for your work having a pretty detailed documentation for the CuBERT source.

However, there appears to be some code missing from compared to what is in [the paper](https://arxiv.org/pdf/2001.00059.pdf). This issue is specifically about the finetuneing code for the downstream tasks.

I image there must exist code somewhere that loaded the dataset jsons and fed them into a BERT training loop, and then evaluated at the end. Could this code be released? (Apologies if I'm missing something if it's already there). It might be just be something that is hacked on top a fork of the BERT repo, and if that's the case, that's totally fine. It'd be really useful to see.

This is not just trivial implementation as some choices like how long functions (> 512 tokens) were finetuned/evaluated might effect downstream performance (I assume just truncating?). This makes it somewhat complicated to recreate/benchmark against CuBERT in followup research I am doing without the source.

See also issue #571 about instructions about using the finetuned models (but not necessarily creating them). Related also is my issue  #581 for missing CuBERT code for the pretraining corpus deduping (which could also be helped with the release of more of the original source).

CC: @adityakanade @maniatis

**Comment by DNGros** [comment]
After some out-of-band discussions with @maniatis confirmed that the finetuning code had to be intentionally omitted due to ties with internal Google source.

However, Petros was thankfully able to confirm some details like that long functions were handled with truncating from the beginning and that eval was done equivalently.

That was enough to replicate finetuning of at least one task I tried. I found the easiest way to do this was using [Huggingface Transformers](https://github.com/huggingface/transformers). First I ran [conversion scripts](https://huggingface.co/transformers/converting_tensorflow_models.html#bert) and then was able to use this as input to `BertForSequenceClassification.from_pretrained()` and finetune with the huggingface [Train](https://huggingface.co/transformers/training.html#trainer) functionality. In [this gist](https://gist.github.com/DNGros/7c2fa0dcf566bd9f3732618669b591dd) I put the bert config used to convert, and the Huggingface API-complient tokenizer I used.

I'm currently in the middle of a messy research code version of playing with all the tasks, so not in a place to share whole pipelines. However, if you're seeing this in the future and run in to difficulties getting it working in your workflow, feel free to @ mention me here and I can give an update on if I had shared any more code for the tasks at that time.

**Comment by sML-90** [comment]
Hello @DNGros 
Thank you for the above info on loading the pre-trained tf checkpoints with huggingface.  I tried as you said and I could convert the model to pytorch. Could you help me on how to use this model to generate embeddings of the inputs as we do with Huggingface LMs.

Thanks in advance!

**Comment by DNGros** [comment]
@sML-90 I don't think this should be a CuBERT specific thing, and should be able to access the embeddings using the normal API. For example the [BertModel](https://huggingface.co/transformers/model_doc/bert.html#transformers.BertModel) and it's subclasses (like BertForSequenceClassification) takes a output_hidden_states argument, and it should give you the embeddings at every layer.

**Comment by sakinafatima** [comment]
Hello @DNGros for such detailed discussion. Actually I am looking for the pytorch_model.bin file of the CuBert Model that I can simply load into my code for fine tuning using AutoModel.from_pretrained( ). Can you explain what files to give as input to this code below  for transformation to PyTorch files? I am new with Bert Models and would appreciate if you can explain what I am missing here and how I can get a pre trained model file of CuBert Model that can be easily loaded.

export BERT_BASE_DIR=/path/to/bert/uncased_L-12_H-768_A-12
transformers-cli convert --model_type bert \
  --tf_checkpoint $BERT_BASE_DIR/bert_model.ckpt \
  --config $BERT_BASE_DIR/bert_config.json \
  --pytorch_dump_output $BERT_BASE_DIR/pytorch_model.bin

**Comment by ElchaabiMohamed** [comment]
Hi @sML-90 ,

Can you tell me if you manage to figure it out. If so, can you tell me the right steps that you follow to get the code embeddings from CuBERT ??

Thanks in advance!
