### ISSUE TITLE
Colorization Transformer: Single GrayScale Image Inference Script?

### ISSUE THREAD

**Issue by ccpocker** [google-research/google-research#583]
@MechCoder
It seems that Colorization Transformer didn't have a script for single grayscale image inference.

I am not familiar with the TF2.0, thus there are also some questions for this open source code:

1. When i try to adapt the sample.py for single image inference, i found it will download the imagenet2012 dataset. Is this nessasary for sample.py?
2. Is there any difference between ”Sampling“ and ”inference“ ?

**Comment by MechCoder** [comment]
Hi @ccpocker, thanks for your interest in our paper. Yes it is true, I did not open source any script for a single gray-scale image inference. However, it should not be too difficult to achieve that.

You can adapt sample.py in the following way.

-  Remove all the code depending on datasets.get_datasets (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L223). This will prevent downloading ImageNet.
-  For the **colorizer**:
    - **input** - 64x64 grayscale image. You need to provide inputs here https://github.com/google-research/google-research/blob/master/coltran/sample.py#L186.
    -  **output['sample']** will output a 64x64 colorized sample. - 
- For the **color upsampler**
    - You need to provide inputs here (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L172)
    - **input: gray_cond** - 64x64 grayscale image.
    - **input: bit_cond** - 64x64 sample from the colorizer.
    -  **output['argmax'] will output a 64x64 RGB image.
 - For the **spatial upsampler**
     - You need to provide inputs here (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L172)
     - **input: gray_cond** - 256x256 grayscale image.
     - **input: low_res**
         - Let the 64x64 output from the color upsampler be `cup_out`
         - Use `low_res=datasets_utils.change_resolution(cup_out, 256)`  to convert it to a blurry 256x256 colorized image.
     - **output['argmax']' - 256x256 final image.

You can save the intermediate images at each stage to disk and then reload them to avoid issues with memory. Let me know if you want to take a stab at it and if you wish to contribute a script. If not, I will try to write one after a couple of weeks.

Re: **inference** vs **sampling**, I think the word inference is used broadly these days. It was used in a probabilistic sense to infer unobserved latent variables but now it can just mean to use the trained model for predictions (incl sampling)

**Comment by ccpocker** [comment]
Hi @MechCoder, thank you so much for such quick reply. 

Yes i will have a try to write a script for single gray-scale image inference  following your instructions. Due to unfamiliar with TF2.0 and limitation of time, i am not sure that i can achieve it.

**Comment by ccpocker** [comment]
hi @MechCoder, i follow your instruction and write a script：

I adopt the sample.py，just change depending on the datasets.get_datasets.

Code are below here:

```python
def load_and_preprocess_image(path):
    image_str = tf.io.read_file(path)
    image = tf.image.decode_image(image_str)
    image = tf.image.grayscale_to_rgb(image)
    example = {}
    example['image'] = image
    return example


def get_dataset_from_dir(config):
    """

    """
    downsample = config.get('downsample', False)
    downsample_res = config.get('downsample_res', 64)
    downsample_method = config.get('downsample_method', 'area')
    dir = config.get('dir', input_dir)
    dir = Path(dir)
    auto = tf.data.experimental.AUTOTUNE

    fileList = sorted([str(file) for file in dir.rglob('*.*')])

    path_ds = tf.data.Dataset.from_tensor_slices(fileList)
    image_ds = path_ds.map(load_and_preprocess_image)
    ds = image_ds.map(lambda x: datasets.preprocess(x, train=False))
    if downsample:
        downsample_part = functools.partial(
            datasets_utils.downsample_and_upsample,
            train=False,
            downsample_res=downsample_res,
            upsample_res=256,
            method=downsample_method)
        ds = ds.map(downsample_part, num_parallel_calls=100)
    ds = ds.batch(1, drop_remainder=True)
    ds = ds.prefetch(auto)
    return ds
```

The output for this line is dict:
https://github.com/google-research/google-research/blob/f2b680b0a8422ba852fd268829a127a41ebe4414/coltran/sample.py#L186 

output=
{'parallel': <tf.Tensor: shape=(1, 64, 64, 3), dtype=uint8，
'auto_sample': <tf.Tensor: shape=(1, 64, 64, 3),dtype=uint8,
'proba': <tf.Tensor: shape=(1, 64, 64, 512), dtype=float32}

when i save the output['parallel'] or output['auto_sample'] are colorful noisy picture( just meanless colorful noisy picture).

It is not the coarsely colorization for the input gray-scale image.

Is there any misunderstanding or wrong for my code?

**Comment by MechCoder** [comment]
Quick questions before I look into detail.

1. Can you verify that the input gray-image has int32 dtype.

2. Is the checkpoint being restored correctly?You can use our latest checkpoints from here (https://console.cloud.google.com/storage/browser/gresearch/coltran/colorizer_v2) which have slightly better results.
You should be able to see logs such as "Producing sample after 601000 training steps." (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L146)

**Comment by ccpocker** [comment]
I debug the code and found the problem is exactly the model don't load the checkpoint correctly.

My log infomation  is "Producing sample after 0 training steps".

The problem is this line:
https://github.com/google-research/google-research/blob/2d5a316a758d2b27b745bc5857503fd822592fa5/coltran/utils/train_utils.py#L186

tf.train.latest_checkpoint(ckpt_dir_) return None

while ckpt_dir_  is the abosolute dir of the colorizer_v2 dir, just like this:

ckpt_dir_  =”/data/glusterfs_hz_cv/11119980/google-research-master/coltran/colorizer_v2“

Any suggestion to fix this problem？

**Comment by MechCoder** [comment]
Could you provide the command-line that you are using to run the code?

**Comment by ccpocker** [comment]
The pwd dir is /data/glusterfs_hz_cv/11119980/google-research-master/
The command-line code is:
```bash
python -m coltran.infer --config=coltran/configs/colorizer.py --mode=infer --logdir=/data/glusterfs_hz_cv/11119980/google-research-master/coltran/colorizer_v2
```

and the infer.py some code is 

```python
def infer(logdir):
    "Executes infering for single gray-scale image"
    logging.info('begingning the infer single image')
    config = FLAGS.config
    batch_size = config.sample.get('batch_size', 1)
    # used to parallelize sampling jobs.
    skip_batches = config.sample.get('skip_batches', 0)
    gen_data_dir = config.sample.get('gen_data_dir', None)
    is_gen = gen_data_dir is not None

    model_name = config.model.get('name')

    dir = config.get('dir', input_dir)
    total_number = len(os.listdir(dir))
    config.sample.num_outputs = total_number

    if not is_gen and 'upsampler' in model_name:
        logging.info('Generated low resolution not provided, using ground '
                     'truth input.')

    # input image to ten
    img_ds = get_dataset_from_dir(config)
    data_iter = iter(img_ds)

    gen_iter = None
    if is_gen:
        pass
    store_samples(data_iter, config, logdir, gen_iter)

def main(_):
    logging.info('Logging to %s.', FLAGS.logdir)
    if FLAGS.mode == 'sample':
        logging.info('[main] I am the sampler.')
        sample(FLAGS.logdir, subset='valid')
    if FLAGS.mode == 'sample_test':
        logging.info('[main] I am the sampler test.')
        sample(FLAGS.logdir, subset='test')
    if FLAGS.mode == 'infer':
        logging.info('[main] i am the inferecen')
        infer(FLAGS.logdir)
    else:
        raise ValueError(
            'Unknown mode {}. '
            'Must be one of [sample, sample_test]'.format(FLAGS.mode))
```

**Comment by MechCoder** [comment]
1. Can you verify that the logdir is passed correctly to the script by printing inside the infer function?
2. Can you also just try
```
ckpt_dir = '/data/glusterfs_hz_cv/11119980/google-research-master/coltran/colorizer_v2'
out = tf.train.latest_checkpoint(ckpt_dir)
print(out)
```

This should print `/data/glusterfs_hz_cv/11119980/google-research-master/coltran/colorizer_v2/model-302`

**Comment by ccpocker** [comment]
Another new day, @MechCoder Good morning!

I check my code and answer is:

1. The logdir is passed correctly to the infer function and this line: https://github.com/google-research/google-research/blob/cbdffab5084e4d823f0c917be01d07969e6460a9/coltran/sample.py#L144
2. I have try your code: and the output is None.  

Firstly, i think i downloaded checkpoint incorrectly, so i have redownload the checkpoint three times from this link you provided, but the output is still None.

The checkpoint dir information in my machine is：
```
total 542905
drwxr-xr-x  2 root root      4096 Mar  4 15:35 ./
drwxr-xr-x 13 root root      4096 Mar  4 15:04 ../
-rw-r--r--  1 root root       997 Mar  3 16:41 coltran-colorizer_v2-checkpoint
-rw-r--r--  1 root root 555911401 Mar  3 16:43 coltran-colorizer_v2-model-302.data-00000-of-00001
-rw-r--r--  1 root root     13521 Mar  3 16:41 coltran-colorizer_v2-model-302.index
```

could you help me check checkpoint information is correctly?

**Comment by MechCoder** [comment]
good morning! I can reproduce the issue. It seems on downloading the checkpoints from the cloud, it adds the prefix ''coltran-colorizer_v2-". 

Can you rename the files, removing the prefixes and make sure that this is the directory information.

```
total 542905
drwxr-xr-x  2 root root      4096 Mar  4 15:35 ./
drwxr-xr-x 13 root root      4096 Mar  4 15:04 ../
-rw-r--r--  1 root root       997 Mar  3 16:41 checkpoint
-rw-r--r--  1 root root 555911401 Mar  3 16:43 model-302.data-00000-of-00001
-rw-r--r--  1 root root     13521 Mar  3 16:41 model-302.index
```

Let me know if it works and I will think of a permanent fix.

**Comment by ccpocker** [comment]
Yes, it works! Thank you so much for quick reply and kind help.

After i finished all the inferecen pipeline, i'll cloesd the issue immediately.

**Comment by MechCoder** [comment]
Thanks @ccpocker. Would you like to contribute a Pull Request with your changes to sample colorizations for single/custom grayscale images? It will be very helpful for others.

**Comment by ccpocker** [comment]
Definitely yes.

**Comment by stopsilver** [comment]
@MechCoder 
Hello, I'm trying to colorize custom images using Coltran. I checked 'colorizer', 'color_upsampler', and 'spatial_upsampler' codes are all working without any error and also checked that each pretrained model is loaded. (checked by `Restoring from ~` and `Producing sample after ### training steps` messages)

But my problem is that colorization doesn't work. My output files(after each steep) only contain bw image with 3 channels. For example, output of coltran_core model has ['parallel', 'auto_sample', 'proba'] keys and 'parallel', 'auto_sample' are gray image in (64, 64, 3) shape. I used gray as input.

Any advice?

**Comment by MechCoder** [comment]
Is this issue relevant? https://github.com/google-research/google-research/issues/619

The input image folder should contain RGB images and not grayscale images. It is converted internally to RGB images here (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L161). See https://github.com/google-research/google-research/issues/619#issuecomment-797261367

Unfortunately right now, there is no direct way of providing grayscale images as input, but should not be very difficult to change that.

**Comment by stopsilver** [comment]
@MechCoder 
Thank you for reply! I thought this paper is about bw to bgr colorization. My mistake.

**Comment by MechCoder** [comment]
Sorry for the confusion. The paper is indeed about bw to rgb conversion. But the codebase does not support it correctly.

If you would like to provide bw images directly, you need to modify the sample.py code as mentioned here (https://github.com/google-research/google-research/issues/583#issuecomment-784115297). Does that help?

@ccpocker Are you still working on this? If not, I can write a script that does this.

**Comment by stopsilver** [comment]
I'm confused. I made a custom dataloader and feeding gray image to colorizer model directly.

which is the line#186 in ([#583 (comment)](https://github.com/google-research/google-research/issues/583#issuecomment-784115297))?
```python
output = model.sample(gray_cond=curr_gray, mode=sample_mode) 
```
or
```python
# Provide low resolution ground truth image.
low_res = next_data['targets_%d_up_back' % downsample_res]
```

Sorry for poor understanding. I don't get the difference btw sample.py and your manual in ([#583 (comment)](https://github.com/google-research/google-research/issues/583#issuecomment-784115297))

**Comment by MechCoder** [comment]
Right, so if you are feeding grayscale images directly, you have to remove this line from the code (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L161).

**Comment by stopsilver** [comment]
For instance, this is my code for `colorizer` part. I deleted that part. Is this right?
```
next_data = next(data_iter)         # next_data.shape [1, 64, 64, 1]
colorizer_model = colorizer.ColTranCore(colorizer_config.model)
colorizer_model(zero, training=False)
checkpoints = train_utils.create_checkpoint(colorizer_model)
train_utils.restore(colorizer_model, checkpoints, log_dir)
a = colorizer_model.sample(gray_cond=next_data, mode='sample')
```

**Comment by MechCoder** [comment]
Yes, does that work?

**Comment by stopsilver** [comment]
Doesn't work neither. I can only get output of 3 channel but gray colored.

**Comment by MechCoder** [comment]
Weird, is it gray for just one image or all images? Are they all of dtype int32?

**Comment by stopsilver** [comment]
I tested with other image sets and it works! Thank you for helping.
Maybe there's some issue in my code when handling certain images. I will look into it and leave comment for others if I find out what was wrong.

**Comment by Dhaskiru04** [comment]
@MechCoder Can you provide the script for single image? I collected some images from google and want to try it this transformer method for my dataset.

**Comment by Dhaskiru04** [comment]
@ccpocker Can you provide the script for single image?

**Comment by MechCoder** [comment]
@Dhaskiru04 Thanks for your interest! I will try to release a script next week.

**Comment by Dhaskiru04** [comment]
@stopsilver Can you share your script? I just want to try this to my dataset?

**Comment by Dhaskiru04** [comment]
@MechCoder Hai, I am trying the script in command prompt where data (single image) and model are in local folder. I didn't use any gpu for this. I got like this 
![Capture](https://user-images.githubusercontent.com/46004330/111960294-924c9a80-8b15-11eb-8487-455d5eb652ab.PNG). I am new to this. Could you help me?

**Comment by Dhaskiru04** [comment]
@MechCoder Hai, I am trying the script in command prompt where data (single image) and model are in local folder. I didn't use any gpu for this. I got like this. I am new to this. Could you help me?
![Capture](https://user-images.githubusercontent.com/46004330/111960516-dfc90780-8b15-11eb-9cc9-ec0677094198.PNG)

**Comment by MechCoder** [comment]
@stopsilver In your snippet over here (https://github.com/google-research/google-research/issues/583#issuecomment-801976617), it is also necessary to restore the ema variables as done here (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L143). It can be crucial to obtain better sample quality.

**Comment by ccpocker** [comment]
@Dhaskiru04 I am so sorry that i can't provide the script due to i am not finished this script.
But for my test, In the first step, colorizer can colorize some picture and some picture still gray after colorizer.

**Comment by MechCoder** [comment]
Hi @ccpocker, If you colorize grayscale images directly, you have to remove the following lines in your script. Otherwise the input provided to the model is wrong. See the issue over here https://github.com/google-research/google-research/issues/619

https://github.com/google-research/google-research/blob/db508b0f9c444012d347b0407c4e398cbbc7705a/coltran/sample.py#L161

**Comment by MechCoder** [comment]
Hello everyone, I released a custom colorization script over here (https://github.com/google-research/google-research/blob/master/coltran/custom_colorize.py) to colorize or recolorize a directory of images.

**Comment by jakbal** [comment]
Script doesn't work:
After setting env variables like:

LOGDIR=/content/coltran/colorizer/
IMG_DIR=/content/grey_cropped/
STORE_DIR=/content/results/
MODE=recolorize

 following error appears:  

**tensorflow.python.framework.errors_impl.FailedPreconditionError: /content/grey_cropped/.ipynb_checkpoints; Is a directory
	 [[{{node ReadFile}}]] [Op:IteratorGetNext]**

Working tree:
![image](https://user-images.githubusercontent.com/37145735/122643495-617a0280-d110-11eb-85e3-1d858d97af5a.png)

**Comment by MechCoder** [comment]
You need to unzip the checkpoints (coltran_cotran.zip) into a separate directory.

And then set logdir to be the path to the colorizer subdirectory.

**Comment by jakbal** [comment]
> You need to unzip the checkpoints (coltran_cotran.zip) into a separate directory.
> 
> And then set logdir to be the path to the colorizer subdirectory.

Thank You, I will try to do so!
