### ISSUE TITLE
tf3d : rio_dataset use instructions cannot be found

### ISSUE THREAD

**Issue by hewittzgh** [google-research/google-research#617]
In tf3d's tf3d_dataset.md, it is mentioned that Waymo open dataset, Scannet Dataset, Rio Dataset are currently supported. I can find the first two usage methods and scripts, but I can’t find the usage method and script of Rio Dataset. The corresponding gin config files and scripts cannot be found in the semantic_segmentation, instance_segmention, and object_detection folders.How can I quickly perform a series of tasks such as model training and evaluation based on the RIO dataset?Thanks!

**Comment by afathi3** [comment]
You are right. I will add config files and script for Rio Dataset soon. I am going to also release trained checkpoints for different tasks and datasets soon.

**Comment by hewittzgh** [comment]
@afathi3 Thank you for your contribution to this great project.Looking forward to the improvement of the project.
