### ISSUE TITLE
[POEM] muliple GPU train

### ISSUE THREAD

**Issue by alex89607** [google-research/google-research#618]
Thanks, for an interesting project! I would like to ask, is it possible to train the model in multiple GPU mode? in the parameter list, I did not find any suitable settings for using more than one graphics card. In a normal startup, only one is used, despite the detection of the available other by the script.

**Comment by jenjsun** [comment]
Hi, thanks for your interest! We don't support this at the moment - but training shouldn't take too long on a single GPU (about 1M steps to converge to something reasonable).
