### ISSUE TITLE
Colorization Transformer: About some bad case

### ISSUE THREAD

**Issue by xc-csc101** [google-research/google-research#619]
@MechCoder 
Thanks for your impressive work. I first sample som images from the imagenet dataset, when i try to visualize the intermediate images of them at stage one, I find some images are successfully colored, but some are failed. I am confused about it. Could you give me some suggestions?

**Comment by MechCoder** [comment]
Hi @xc-csc101 thanks for your interest in our paper.

Could you provide some examples?

**Comment by MechCoder** [comment]
Could you also try with our latest checkpoints at https://storage.cloud.google.com/gresearch/coltran/coltran.zip? They give slightly better results.

**Comment by xc-csc101** [comment]
Yes, I use the latest checkpoints from here (https://console.cloud.google.com/storage/browser/gresearch/coltran/colorizer_v2). I send some example to your email. Besides, the code reference this issue #583.

**Comment by xc-csc101** [comment]
With the help of the author, the problem is that the input image folder should contain RGB images rather than grayscale images. In this line (https://github.com/google-research/google-research/blob/master/coltran/sample.py#L161), the RGB images are converted to gray images. Since the problem is solved, I close this issue. Thanks for the kind help! @MechCoder
