### ISSUE TITLE
fastconvnets: invalid tensor buffer

### ISSUE THREAD

**Issue by lutzroeder** [google-research/google-research#653]
The [fastconvnets](https://github.com/google-research/google-research/tree/master/fastconvnets) models contain a tensor with invalid data?

```bash
~: wget https://storage.googleapis.com/fast-convnets/tflite-models/mbv1_100_90_12b4_684.tflite
~: python
```
```python
>>> import tensorflow as tf
>>> interpreter = tf.lite.Interpreter(model_path="mbv1_100_90_12b4_684.tflite")
>>> interpreter.allocate_tensors()
>>> all_layers_details = interpreter.get_tensor_details()
Segmentation fault (core dumped)
```
```python
>>> tensor = model.Subgraphs(0).Tensors(14)
>>> tensor.ShapeAsNumpy()
array([64,  1,  1, 32], dtype=int32)
>>> buffer = model.Buffers(tensor.Buffer())
>>> buffer.DataLength()
820
```

@tgale96 @codgeek

lutzroeder/netron#681

**Comment by minghaoBD** [comment]
Hi Lutz, 

I have exactly the same issue with you when parsing this tflite model but don't how to solve it. Could you share your solutions to it? Thank you.

Minghao

**Comment by lutzroeder** [comment]
@minghaoBD this issue has not been resolved. Please open a new issue.
