### ISSUE TITLE
[depth_and_motion_learning] Inference

### ISSUE THREAD

**Issue by wmy111000** [google-research/google-research#662]

**Comment by wmy111000** [comment]
> After training, how can I infer my model?
> Should I use the function infer_depth(rgb_image, params) in depth_motion_field_model.py to get depth image?

**Comment by Lostinecho** [comment]
Hi, did you find a solution to this? I also did not find any files about inference.

**Comment by WeihengXia0123** [comment]
> Hi, did you find a solution to this? I also did not find any files about inference.

You can find another issue with the same problem: 
[#issue 474](https://github.com/google-research/google-research/issues/474)
