### ISSUE TITLE
Pass data to tensorboard (kws_streaming)

### ISSUE THREAD

**Issue by ntyoshi** [google-research/google-research#666]
Hi,
I'm curious of the output of each layers and I want to visualize it on Tensorboard.
I heard there are some ways to pass data to Tensorboard but what is the best way in the kws_streaming project?
I wonder if you guys have some recommended ways.
As far as I see, I guess I need to add some data to [this line](https://github.com/google-research/google-research/blob/0667f4c48f3920f0fa7ee85a54f5c3def92e4f97/kws_streaming/train/train.py#L149) in kws_streaming/train/train.py.  

Thank you!

**Comment by rybakov** [comment]
Yes, you can add more log info in [line1](https://github.com/google-research/google-research/blob/0667f4c48f3920f0fa7ee85a54f5c3def92e4f97/kws_streaming/train/train.py#L149)

**Comment by ntyoshi** [comment]
Do you know the good way to pass each layers output?
Do I have to modify layers modes script like [cnn.py](https://github.com/google-research/google-research/blob/0667f4c48f3920f0fa7ee85a54f5c3def92e4f97/kws_streaming/models/cnn.py)?

**Comment by rybakov** [comment]
There is no need to modify the model to access the outputs of every layer because the model is based on functional keras api so you can iterate over layers and get any output, please have a look at [link](https://stackoverflow.com/questions/41711190/keras-how-to-get-the-output-of-each-layer).

**Comment by ntyoshi** [comment]
OK. Let me try it. It might take for a while.
If you see other examples that look good, please share it kindly. 
Anyway thanks for your advice!

**Comment by ntyoshi** [comment]
I inserted following code [here](https://github.com/google-research/google-research/blob/2f73ba5cdb6a829f5458f58f94d893e969bf74e8/kws_streaming/train/train.py#L153) and I could see data on TensorBoard.
Actually I know this is not good codes but for now let me share just in case.
I wrote for only the 1st batch of the 1st layer's output.

```
if training_step == start_step
  inp = model.input                                           # input placeholder
  outputs = [layer.output for layer in model.layers][1:]          # all layer outputs except for input layer
  functors = [K.function([inp, K.learning_phase()], [out]) for out in outputs]    # evaluation functions
  layer_outs = [func([train_fingerprints,1.]) for func in functors]
  
  # input data
  loop=0
  for i in train_fingerprints[0]:
    train_writer.add_summary(
        tf.Summary(value=[
                          tf.Summary.Value(
                              tag='input_' +  str(training_step),
                              simple_value=i)
                    ]) ,loop)
    loop = loop + 1
  
  # 1st layer's output
  loop = 0
  for o in layer_outs[0][0][0]:
    train_writer.add_summary(
                  tf.Summary(value=[
                          tf.Summary.Value(
                              tag='output_' +  str(training_step),
                              simple_value=o)
                    ]) ,loop)
    loop = loop + 1
```

I'm going to close this issue soon unless there are any problems but if anyone have better ideas, please share it.
Thank you.
