### ISSUE TITLE
[automl-zero] failed to build with the last commit

### ISSUE THREAD

**Issue by maxoodf** [google-research/google-research#667]
I can not build AutoML-Zero since the following dependency was added to proto files (commit 3778f19) -
`import "devtools/staticanalysis/pipeline/analyzers/proto_best_practices/proto/optouts.proto";`

**Comment by dineshdaultani** [comment]
This looks similar as issue #647. There's no resolution as of now though.

**Comment by crazydonkey200** [comment]
Thanks for noticing this. This issue should be fixed now by this [commit](https://github.com/google-research/google-research/commit/f3332cf769f20b1a4fffa9fecc630af00aab902a). Please pull the newest version and see if it works.

**Comment by maxoodf** [comment]
Thanks, built successfully.
