### ISSUE TITLE
Enas_lm child model

### ISSUE THREAD

**Issue by HaleyQH** [google-research/google-research#67]
In the child.py file, why w_skip[0] is not used for L2 weight reg ?
var_s = [w_prev] + w_skip[1:]

https://github.com/google-research/google-research/blob/43058538eeee450e6cdebeb960a78832b1673db3/enas_lm/src/child.py#L69

Does w_skip[0] means the weight of node 1 and node 2 (as the red arrow shows )?

![enas](https://user-images.githubusercontent.com/52318628/67278836-5ebea880-f4fc-11e9-8601-e959b3b123c3.jpg)

**Comment by ZhiqingXiao** [comment]
I also noticed bugs in calculating the L2 regularization.

In child.py:
https://github.com/google-research/google-research/blob/master/enas_lm/src/child.py#L318
```
self.l2_reg_loss = tf.add_n([tf.nn.l2_loss(w ** 2) for w in var_s])
```
The regularization is implemented as "l4" regularization.

However in fixed_lib is correct:
https://github.com/google-research/google-research/blob/master/enas_lm/src/tpu/fixed_lib.py#L409

@phthhieu
@melodyguan
