### ISSUE TITLE
(tf3d) 3d sparse convnet layer on simple data ?

### ISSUE THREAD

**Issue by StephaneKazmierczak** [google-research/google-research#701]
Hello, 

I recently manage to get tf3d to compile on my machine, win10/wsl, was a bit of a challenge. 
I am working on a 3d encoder / decoder using voxel type data [batch, voxel_idx, voxel_idz, voxel_idy, feature_channels] using keras Conv3d / Conv3dtranspose. My data is very sparse and I was under the impression that the sparse conv 3d block could help. 

I don't have access to the dataset to run your examples yet, so I only looked at your test cases, but I am not really getting how voxel_feature, voxel_indices, num_valid_voxels works. Do you have additional explanations on what they are and how they are related ? 
Also, probably none of the sparse layers would work with my data format, right ?  

Best,

**Comment by donnybaby-hub** [comment]
Just hanging out eh?

**Comment by donnybaby-hub** [comment]
Long as we understand each other I’m good man a living like this until it upsets the balance

**Comment by StephaneKazmierczak** [comment]
not sure that I am getting what you mean with the balance thing, sorry this thread can be remove. I figure I wont get much help here but I am slowly starting to understand while digging into the code, so that is ok.
