### ISSUE TITLE
ScaNN normalizing dataset pre-training

### ISSUE THREAD

**Issue by Audida** [google-research/google-research#706]
As mentioned in [Accelerating Large-Scale Inference with Anisotropic Vector Quantization](https://arxiv.org/abs/1908.10396)

> "MIPS is equivalent to cosine similarity search when all datapoints are equal-norm, so we adopt our technique to cosine similarity search by unit-normalizing all datapoints at training time." 

Does this mean that it is not necessary to normalize dataset pre-training as seen in example code?

**Comment by donnybaby-hub** [comment]
Does this mean it's OK to normalize data set even if it's not cutting through?￼

**Comment by donnybaby-hub** [comment]
As seen in the example code[](https://music.apple.com/us/music-movie/spatial-audio-on-apple-music/1566497432)￼

**Comment by Audida** [comment]
Thank you baby donny, your very helpfull ;)
