### ISSUE TITLE
[Scann] Building from source failed

### ISSUE THREAD

**Issue by gyd-a** [google-research/google-research#720]
1. Error message:

ERROR: /root/.cache/bazel/_bazel_root/ef4c81d6fdf57bdb4d4cf1931e4d510a/external/bazel_tools/src/tools/launcher/BUILD:9:14: in cc_binary rule @bazel_tools//src/tools/launcher:launcher: When using LTO. The feature supports_start_end_lib must be enabled.

2. Compile environment:
use docker image: centos7-gcc9-cmake3, CentOS Linux release 7.7.1908 (Core) , gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), clang version 8.0.1, bazel 4.1.0

**Comment by tirthptl** [comment]
Hi @gyd-a what was the Root cause and solution to the issue?
