### ISSUE TITLE
Google Colab notebook for coltran

### ISSUE THREAD

**Issue by mhoangvslev** [google-research/google-research#762]
Hi all,

I create a notebook that allows you to use pre-trained model to colorise your image with just few click!
https://colab.research.google.com/drive/1c8UZL3CkczbIltDxjDfFbq9Y0RnMv93o?usp=sharing

The input must be 64x64 or 128x128. Is there a way to make it work with image of any size?

**Comment by NusratNB** [comment]
Hello, how about setting the shape of the input Tensor to the None?

**Comment by MechCoder** [comment]
@mhoangvslev Thanks for your work! Would you like your colab to be part of the repository?

In our paper and in the released checkpoints the final output resolution is 256x256.

Even higher resolution output can be obtained by some tricks. In Y Cb Cr space, you could upsample the 256x256 Cb and Cr channels using standard tf.image.resize methods and combine them with the high resolution 512x512 Y channel.

**Comment by mhoangvslev** [comment]
@MechCoder Gladly. I would like to make it work with image of any size, not just square and length as power of 2.

**Comment by MechCoder** [comment]
One (untested) code snippet to try would be:

```
# output is the output of the spatial upsampler.
# gray is the high resolution grayscale iamge
output = tf.expand_dims(output, axis=0)
resized = tf.image.resize(output, size=(new_h, new_w), preserve_aspect_ratio=True)
resized_yuv = tf.image.rgb_to_yuv(resized)
y, u, v = tf.unstack(resized_yuv, axis=-1)

high_res = tf.stack([gray, u, v], axis=-1)
```

**Comment by fengwang** [comment]
@mhoangvslev Can you please fix the dead colab link?

**Comment by mhoangvslev** [comment]
I regret to announce that I lost the file. I will repost the link here when I have time
