### ISSUE TITLE
Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] 

### ISSUE THREAD

**Issue by danhernest-rist** [google-research/google-research#763]
Download from https://github.com/bazelbuild/rules_cc/archive/master.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip]

**Comment by NicMcPhee** [comment]
It looks like `master.zip` has been renamed to `main.zip`. Changing that in `WORKSPACE` however, doesn't fix the problem as there seem to be other references with the old naming.

**Comment by danhernest-rist** [comment]
Updated the WORKSPACE with "main" instead of "master" only for rules_cc and rules_proto and now it's back to normal (in my situation for automl_zero)

http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-main",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/main.zip"],
)

http_archive(
    name = "rules_proto",
    strip_prefix = "rules_proto-main",
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/main.zip",
    ],
)
