### ISSUE TITLE
[POEM] 3d keypoints in training

### ISSUE THREAD

**Issue by andresherrera97** [google-research/google-research#776]
Hello, 
Looking at your PR-VIPE code I don't fully understand why the 3d keypoints are needed if the idea is to embedd the 2d keypoints to the respective action the subject is doing.

**Comment by andresherrera97** [comment]
Reading further the code I saw that it is used to generate more 2D keypoints. However, changing the code to only use 2D input gives issues in some parts such as the triplet loss calculation, how can I adapt the code to use 2D keypoints in that part? Because using only 2D keypoints I don't have anchor_keypoints_3d, positive_keypoints_3d ot the masks.

` triplet_loss, triplet_loss_summaries = (
                             loss_utils.compute_keypoint_triplet_losses(
                                                 anchor_embeddings=triplet_anchor_embeddings,
                                                 positive_embeddings=triplet_positive_embeddings,
                                                 match_embeddings=triplet_positive_embeddings,
                                                 anchor_keypoints=anchor_keypoints_3d,
                                                 match_keypoints=positive_keypoints_3d,
                                                 margin=FLAGS.triplet_loss_margin,
                                                 min_negative_keypoint_distance=(
                                                     configs['min_negative_keypoint_distance']),
                                                 use_semi_hard=FLAGS.use_semi_hard_triplet_negatives,
                                                 exclude_inactive_triplet_loss=(
                                                     FLAGS.exclude_inactive_triplet_loss),
                                                 anchor_keypoint_masks=anchor_keypoint_masks_3d,
                                                 match_keypoint_masks=positive_keypoint_masks_3d,
                                                 embedding_sample_distance_fn=(
                                                     configs['triplet_embedding_sample_distance_fn']),
                                                 keypoint_distance_fn=configs['keypoint_distance_fn'],
                                                 anchor_mining_embeddings=triplet_anchor_mining_embeddings,
                                                 positive_mining_embeddings=triplet_positive_mining_embeddings,
                                                 match_mining_embeddings=triplet_positive_mining_embeddings,
                                                 summarize_percentiles=FLAGS.summarize_percentiles
                                                 )
                             )`

**Comment by jenjsun** [comment]
Hi - thanks for your interest! First, the main idea is to embed the 2D poses such that if they are projected from similar 3D poses, then they are close together in the embedding space (See Fig 1 of our paper: https://arxiv.org/pdf/1912.01001.pdf). 

To use 2D keypoints only, there are a few things you need to do:
- Set this flag to -1 (https://github.com/google-research/google-research/blob/d26ed752ca5f276f0c35a2d55e213b7cb2ea9339/poem/pr_vipe/train_base.py#L100-L101). The input will still try to read in 3D keypoints, so you can add some dummy ones (ex: set 3D keypoints to all 0s).
- Set this flag to 2D_INPUT (https://github.com/google-research/google-research/blob/d26ed752ca5f276f0c35a2d55e213b7cb2ea9339/poem/pr_vipe/train_base.py#L49) to disable camera augmentation.
