### ISSUE TITLE
Coltran notebook not loading checkpoints

### ISSUE THREAD

**Issue by Sandv** [google-research/google-research#781]
Hi, 

There is a small issue with the notebook leading to nonfunctioning of the colorization.

Changing the line
os.environ["LOGDIR"] = "/content/google-research/coltran/logdir/"
to
os.environ["LOGDIR"] = "/content/google-research/coltran/logdir/coltran"

fixes it. 

Thank you very much!
Veit

**Comment by MechCoder** [comment]
@mhoangvslev Could you please make this edit to your notebook? Thanks in advance!

**Comment by mhoangvslev** [comment]
> @mhoangvslev Could you please make this edit to your notebook? Thanks in advance!

Done!

**Comment by MechCoder** [comment]
Thanks!

@Sandv Can the issue be closed?
