### ISSUE TITLE
Inference for Poem

### ISSUE THREAD

**Issue by farazBhatti** [google-research/google-research#795]
I wanted to get inference for Poem repository, but it seems that it does not provide and pre-trained model. Can anyone please  tell how should I get inference ? Thanks

**Comment by jenjsun** [comment]
Hello, you can contact me by email (jjsun@caltech.edu) for a pre-trained model. We have the inference script here: https://github.com/google-research/google-research/blob/master/poem/pr_vipe/infer.py

**Comment by farazBhatti** [comment]
Hi @jenjsun , thanks for the consideration. Ive emailed you. Thanks

**Comment by farazBhatti** [comment]
For any one looking for  pre trained model. Here is the link : https://github.com/google-research/google-research/issues/457#issuecomment-863501473
