### ISSUE TITLE
[TFT] Computing Validation Loss: Zero-Dimensional arrays cannot be concatenated

### ISSUE THREAD

**Issue by Hinnerk8** [google-research/google-research#801]
Hey, 
i am trying to run the temporal fusion transformer network on my own data. 

The test with the default datasets volatility and traffic worked out without any problem. 

When using my own dataset, i receive an error when the network starts computing the validation loss: 

`Done.
Computing best validation loss
Traceback (most recent call last):
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Noah\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Noah\tft\script_train_fixed_params.py", line 238, in <module>
    use_testing_mode=True)  # Change to false to use original default params
  File "C:\Users\Noah\tft\script_train_fixed_params.py", line 151, in main
    val_loss = model.evaluate(valid)
  File "C:\Users\Noah\tft\libs\tft_model.py", line 1189, in evaluate
    raw_data = self._batch_data(data)
  File "C:\Users\Noah\tft\libs\tft_model.py", line 763, in _batch_data
    data_map[k] = np.concatenate(data_map[k], axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: zero-dimensional arrays cannot be concatenated`

I followed the instruction of creating a new data-formatterclass for my experiment. I added column-definitions equal to those in traffic and volatility experiment: 
`_column_definition = [
      ('id', DataTypes.REAL_VALUED, InputTypes.ID),
      ('Minutengesamt', DataTypes.REAL_VALUED, InputTypes.TIME),
      ('Gasmengenstrom', DataTypes.REAL_VALUED, InputTypes.TARGET),
      ('Gesamtwasser', DataTypes.REAL_VALUED, InputTypes.KNOWN_INPUT),
      ('Gesamtschlamm', DataTypes.REAL_VALUED, InputTypes.KNOWN_INPUT),
      ('Tag', DataTypes.CATEGORICAL, InputTypes.KNOWN_INPUT),
      ('Jahr', DataTypes.CATEGORICAL, InputTypes.KNOWN_INPUT),
      ('Stunde', DataTypes.CATEGORICAL, InputTypes.KNOWN_INPUT),
      ('Minute', DataTypes.CATEGORICAL, InputTypes.KNOWN_INPUT),
      ('CatID', DataTypes.CATEGORICAL, InputTypes.STATIC_INPUT),
  ]`

And I am splitting my dataset: 
`def split_data(self, df, valid_boundary=26300, test_boundary=30700):
    """Splits data frame into training-validation-test data frames.

    This also calibrates scaling object, and transforms data for each split.

    Args:
      df: Source data frame to split.
      valid_boundary: Starting year for validation data
      test_boundary: Starting year for test data

    Returns:
      Tuple of transformed (train, valid, test) data.
    """

    print('Formatting train-valid-test splits.')

    index = df['indall']
    train = df.loc[index < valid_boundary]
    valid = df.loc[(index >= valid_boundary) & (index < test_boundary)]
    test = df.loc[(index >= test_boundary) & (index <= 34631)]`

I did not change anything else in comparison to the volatility default experiment. 
My complete dataset consists out of 35136 rows - so i left out the last lines, like in the volatility experiment it is performed. Although i dont understand so far, why this is done. 

Can somebody explain to me, what I would need to change and why those last lines are left out?

Thank you in advanced!
Hinnerk8

**Comment by Hinnerk8** [comment]
Problem solved - I did not saw, that the id is kind of batched too.

**Comment by 1369520077** [comment]
> Hinnerk8

Yes you go ahead do that.
ek48fmp982op2290nr:Ff
]reFR:Ff.Ff.WEW*WFwefiufnw
