### ISSUE TITLE
[kws_streaming] Trained Model SVDF

### ISSUE THREAD

**Issue by vishalkevat007** [google-research/google-research#804]
@rybakov Can you please provide the pretrained model or the best_weights for the KWS_Streaming SVDF model or any other method? 
I couldn't trained it completely on colab due to limitations. If it is possible please provide it, I need it urgently.

**Comment by rybakov** [comment]
colab examples were created just for demo purposes and getting familiar with this lib. 
You should follow any example in [experiments](https://github.com/google-research/google-research/tree/master/kws_streaming/experiments), e.g. to reproduce results from our paper you need to run [kws_experiments_paper_12_labels.md](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md). 
Most models have small size, so you could train them even on laptop cpu (you can control training time by changing how_many_training_steps). 
I attached svdf model trained with recipe from [kws_experiments_paper_12_labels.md](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md).
I trained it with below command:
```shell
$CMD_TRAIN \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/svdf/ \
--mel_upper_edge_hertz 7600 \
--how_many_training_steps 20000,20000,20000,20000 \
--learning_rate 0.001,0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 80 \
--dct_num_features 30 \
--resample 0.15 \
--alsologtostderr \
--time_shift_ms 100 \
--train 1 \
svdf \
--svdf_memory_size 4,10,10,10,10,10 \
--svdf_units1 256,256,256,256,256,256 \
--svdf_act "'relu','relu','relu','relu','relu','relu'" \
--svdf_units2 128,128,128,128,128,-1 \
--svdf_dropout 0.0,0.0,0.0,0.0,0.0,0.0 \
--svdf_pad 0 \
--dropout1 0.0 \
--units2 '' \
--act2 ''
``` 

Trained model is in [svdf.zip](https://github.com/google-research/google-research/files/7095031/svdf.zip)

**Comment by vishalkevat007** [comment]
Thank you @rybakov
