### ISSUE TITLE
[KWS_Streaming] Error while training crnn model

### ISSUE THREAD

**Issue by vishalkevat007** [google-research/google-research#807]
I tried to train the crnn model mentioned in the recipe [kws_experiments_paper_12_labels.md](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md#crnn)

When I run the $CMD_TRAIN \ with all the parameters as mentioned, I am getting error

> InvalidArgumentError: Node 'training/Adam/gradients/gradients/gru/cell/while_grad/gru/cell/while_grad': Connecting to invalid output 51 of source node gru/cell/while which has 51 outputs. Try using tf.compat.v1.experimental.output_all_intermediates(True).

How can I train this model in the bash terminal as mentioned in the recipe?

**Comment by rybakov** [comment]
It looks like a bug in tf, introduced in the latest version, please feel free to file a bug for [tf](https://github.com/tensorflow/tensorflow/issues). As error suggested, try using tf.compat.v1.experimental.output_all_intermediates(True).
Please insert:
```
  if flags.model_name=='crnn':
    tf.compat.v1.experimental.output_all_intermediates(True) 
```
into [line 72](https://github.com/google-research/google-research/blob/master/kws_streaming/train/train.py#L72)

**Comment by rybakov** [comment]
I submitted above fix, please pull the latest version of [kws_streaming](https://github.com/google-research/google-research/tree/master/kws_streaming).

**Comment by vishalkevat007** [comment]
> I submitted above fix, please pull the latest version of [kws_streaming](https://github.com/google-research/google-research/tree/master/kws_streaming).

Thank you @rybakov. Its working now.
