### ISSUE TITLE
[KWS_Streaming] Conversion to streaming with internal and external states

### ISSUE THREAD

**Issue by vishalkevat007** [google-research/google-research#812]
Hey @rybakov 
I have trained the SVDF model as per the mentioned recipe. I want to know how the model is getting converted to streaming with internal states and external states. I am searching for the code which does model conversion to streaming mode. Where I can find the written code flow of the conversion in the repo?

**Comment by rybakov** [comment]
If you trained model with description from [experiments](https://github.com/google-research/google-research/tree/master/kws_streaming/experiments) then your model already converted to streaming mode and stored in folder (both model artifacts with test accuracy) which you used for training: folder structure is described in the end on [link](https://github.com/google-research/google-research/tree/master/kws_streaming)

If you need more details about how conversion to streaming is done, then please have a look at [function](https://github.com/google-research/google-research/blob/master/kws_streaming/models/utils.py#L266)

**Comment by vishalkevat007** [comment]
Oh okay!
Thanks @rybakov
