### ISSUE TITLE
[POEM] Run infer.py needs csv

### ISSUE THREAD

**Issue by farazBhatti** [google-research/google-research#818]
Hi, can you please share a sample input CSV(the one with normalized x, y coordinates) in order to run infer.py? Although the procedure to make it is given in infer.py code it seems that i can't figure out how to make one. I need to run inference and for that 2D coordinates, a CSV file is needed. 
Thanks

**Comment by jenjsun** [comment]
I saw that there was a discussion here: https://github.com/google-research/google-research/issues/716#issuecomment-919711761 and another user shared a CSV file.
