### ISSUE TITLE
Missing reference & comparison in iALS++ paper?

### ISSUE THREAD

**Issue by tohtsky** [google-research/google-research#889]
Hi @walidk, congratulations for your exciting new papers about iALS! Its regularization scheme seems clever and effective.

Although I'm not sure if this is the right place ask this question, I believe that [a conjugate gradient descent based algorithm](http://rs1.sze.hu/~gtakacs/download/recsys_2011_draft.pdf) to solve iALS problem has

1. exactly the same computational complexity with iCD and iALS++ method. (However, it seems that iCD paper does not  refer to this paper either)
2. highly vectorizable implementation (like the one in [implicit](https://github.com/benfred/implicit))

Is there any reason why this paper is not referenced?

**Comment by walidk** [comment]
Hi @tohtsky
Thank you for bringing this work to our attention. We will update our paper to include a discussion/comparison with the CG-based method of Takács et al.
One can also combine the CG method with iALS++ as follows. In iALS++, we solve a sequence of least squares problems on different subspaces. In our experiments we used Cholesky as a solution method, but that can be replaced by a CG-based method. This could lead to a further speedup.

**Comment by tohtsky** [comment]
Thanks for your reply, the work of Takács et al. is very effective in optimizing iALS loss, but unfortunately for some reason is not very well known.

> In our experiment, we used Cholesky as a solution method, but it can be replaced by a CG-based solution.

That's brilliang! I am looking forward to the updated version.
