### ISSUE TITLE
[ALBERT] Attribute Error

### ISSUE THREAD

**Issue by zhang-zeyu** [google-research/google-research#89]
Hello,

Thank you for the useful tools. Here is a error when I run run_classifier_with_tfhub.py:

`Error while finding module specification for 'run_classifier_with_tfhub.py' (AttributeError: module 'run_classifier_with_tfhub' has no attribute '__path__')`

Could you guys give me some hints? Thanks!

**Comment by stefan-it** [comment]
You should try to call the albert code from the root directory (not from the `albert` folder):

```bash
python -m albert.run_classifier_with_tfhub [params]
```

But there are some issues with the code, see for example #86 

So I think we should give the albert team a little more time :)

**Comment by zhang-zeyu** [comment]
@stefan-it Thank you very much!

**Comment by zhang-zeyu** [comment]
@stefan-it Hi, I tried to call albert code from the parent directory of albert (i.e Projects/albert) , but still  `Error while finding module specification for 'albert.run_classifier_with_tfhub.py' (AttributeError: module 'albert.run_classifier_with_tfhub' has no attribute '__path__')` 
I think it's might not the directory problem, could you please give me some suggestions?

**Comment by stefan-it** [comment]
Could you try to remove the `.py` ending when calling the command 🤔 Then it should work 🤗

**Comment by zhang-zeyu** [comment]
@stefan-it Sorry to reply late, it works, thank you!
