### ISSUE TITLE
[smurf] Batch size > 1 doesn't work

### ISSUE THREAD

**Issue by remimar** [google-research/google-research#895]
Hi,

Thanks for sharing your work !

You say in your paper that the batch size is 8 but your code only works with batch size 1. Are you going to release a version that works with batch size > 1 ?

**Comment by AustinCStone** [comment]
There is an assumption in the code of batch size 1 per GPU. You run into memory issues trying to squeeze more images onto an individual V100 GPU anyway, so this is not very limiting.

In our work, we trained with an 8 GPU machine. In the released code, you should be able to train with a batch size equal to 8 if you have 8 GPUs available.

**Comment by remimar** [comment]
Ok, thanks for your answer.
