### ISSUE TITLE
[KWS_Streaming] how to use gpu to train model ?

### ISSUE THREAD

**Issue by dungnguyen98** [google-research/google-research#912]
Hi, thanks for your great repository. I have a question: How can use gpu when I train kws_streaming model? (When I do training, I check my gpu usage, and nothing happened). I don't find any param out which talk about it? Can you give me some advices?

**Comment by rybakov** [comment]
@dungnguyen98 please have a look at [discussion](https://github.com/google-research/google-research/issues/679#issuecomment-830774560).

**Comment by dungnguyen98** [comment]
I got it! Thank you!
