### ISSUE TITLE
[vatt] Argument error in data processing with dmvr

### ISSUE THREAD

**Issue by Adam-fei** [google-research/google-research#917]
Hi @hassanhub, sorry for the interruption.

I'm trying to reproduce the result of vatt, but ran into some problem:

In your code, you used the dmvr package to process the video data.
When I run the following command:
`python -m vatt.main --task=finetune --mode=eval --model_dir=/path/to/model --model_arch=vit_base --strategy_type=mirrored`
An error occured:

> ./vatt/data/processing.py", line 579, in add_audio
> TypeError: add_audio() got an unexpected keyword argument 'preprocessor_builder'

I noticed that **modalities** is imported from **dmvr** package. So I checked the source code [here](https://github.com/deepmind/dmvr/blob/master/dmvr/modalities.py), the **add_audio** function has no argument `preprocessor_builder` indeed.

Besides, There is no argument `sample_rate`, `target_sample_rate` in **add_audio** too, but they are used in ./vatt/data/processing.py", line 579.

The dmvr package I installed is version 0.0.1.

Is something wrong with the vatt code? Or simply I did something wrong?

Thanks :)

**Comment by Adam-fei** [comment]
Also, in ./vatt/README.md, Data section:

> Embeddings and Vocabulary
> Depending on the configuration, you might need the pre-trained text embeddings and vocuabulary. Please download this file and extract it under vatt/.

above hyperlink leads to **Forbidden Error 403**, Could you please fix it?

Thank you!

**Comment by hassanhub** [comment]
Thanks for your feedback.
Regarding the add_audio issue, there is a mismatch between the latest internal version and the public version of DMVR. I will communicate this with DMVR authors to resolve the issue. In the meantime, you can simply bypass it by removing those args.

Regarding the embeddings and vocabs, I made the file public. You should have access now.
Please let me know if you ran into any other issues.

**Comment by Adam-fei** [comment]
Thank you for your reply! I met another issue here:

I downloaded the following checkpoint file, and try to use it to evaluate the Kinetics-400 result

![image](https://user-images.githubusercontent.com/18185114/146738933-69bedbed-d025-4ec1-ab4e-be506640847b.png)

I used this command line:
`python -m vatt.main --task=finetune --mode=eval --model_dir=./my_output --model_arch=vit_base --strategy_type=mirrored --override_checkpoint=/PATH/TO/FILE/vision_vatt_finetune_vit_base_k400_modality_specific_pretrain_ckpt-100000`

But I got this error message indicates that the value shape is incompatible with the model network:

> ValueError: Cannot assign value to variable ' video_module/vit_base/spatio_temporal_embeddings/horizontal_position_embeddings/embeddings:0': Shape mismatch.The variable shape (14, 768), and the assigned value shape (20, 768) are incompatible.

 I tried to change the "14" argument in video.py and uvatt.py, but the error still occur. What should I do?

**Comment by hassanhub** [comment]
You don't need to tweak uvatt.py for finetune. Finetune only uses video.py or audio.py

Can you please send me your config below:
- video.py: ViTBase.spatial_patch_size
- video.py: ViTBase.max_vertical_buckets
- video.py: ViTBase.max_horizontal_buckets
- dataset.py: Finetune.frame_size

Alternatively, please upload your `params.yaml` somewhere and send me the link so that I could take a look.

I will upload the pre-set configs in the future. But for now please bare with us with setting the config flags manually.

**Comment by Adam-fei** [comment]
I see. I thought the config is pre-set and I could just hit the run Button :)

Now my config is as follow:

video.py: ViTBase.spatial_patch_size=16
video.py: ViTBase.max_vertical_buckets=14
video.py: ViTBase.max_horizontal_buckets=14
dataset.py: Finetune.frame_size=224

As for params.yaml, I did not use any *.yaml file as config file, since there is no config_file mentioned in the README.md. Where can I find it?

**Comment by hassanhub** [comment]
Please change it to the following:

video.py: ViTBase.spatial_patch_size=16
video.py: ViTBase.max_vertical_buckets=20
video.py: ViTBase.max_horizontal_buckets=20
dataset.py: Finetune.frame_size=224

`Side note`: Although we wrote the `Position Encoding Lookup` module to be dynamic in terms of the input size (using interpolation), it's recommended to use a frame size of 320 for the action recognition models, because they were trained with this size and the accuracy of pos embd lookups decreases by using interpolation. If you are fine-tuning, you don't need to worry about it. But if you just want to evaluate the model, please use `dataset.py: Finetune.frame_size=320`.

**Comment by Adam-fei** [comment]
Thank you so much for the tips!

I will post the newest update, thx again :)

**Comment by Adam-fei** [comment]
Hi, I encountered another problem.

I followed the [dmvr example](https://github.com/deepmind/dmvr/tree/master/examples) to generate the dataset.
And changed the corresponding code so the code can read the correct path of data.

But when I run the vatt evaluation process, it would raise following error:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
>   (0) INVALID_ARGUMENT:  Name: <unknown>, Key: image/encoded, Index: 0.  Number of values != expected.  values size: 91 but output shape: []
>          [[{{node ParseSingleSequenceExample/ParseSequenceExample/ParseSequenceExampleV2}}]]
>          [[MultiDeviceIteratorGetNextFromShard]]
>          [[RemoteCall]]
>          [[IteratorGetNext_3]]
>          [[model/video_module/vit_base/spatio_temporal_embeddings/strided_slice_5/_1]]
>   (1) INVALID_ARGUMENT:  Name: <unknown>, Key: image/encoded, Index: 0.  Number of values != expected.  values size: 91 but output shape: []
>          [[{{node ParseSingleSequenceExample/ParseSequenceExample/ParseSequenceExampleV2}}]]
>          [[MultiDeviceIteratorGetNextFromShard]]
>          [[RemoteCall]]
>          [[IteratorGetNext_3]]
>   (2) CANCELLED:  Function was cancelled before it was started
> 0 successful operations.
> 0 derived errors ignored. [Op:__inference_evaluation_step_21087]
> 
> Function call stack:
> evaluation_step -> evaluation_step -> evaluation_step

I located the error at line150 in file ./vatt/data/loading.py where the object generate by command `factory.make_dataset()` cannot be read. The minimize pseudocode is as follow:

```
dataset =  factory.make_dataset(
              shuffle=self.shuffle,
              num_epochs=self.num_epochs,
              batch_size=per_replica_batch_size,
              padded_batch=False,
              drop_remainder=True,
              keep_key=False,
              override_preprocess_fn=None,
              )
iter_data = iter(dataset)
next(iter_data) // this would trigger the error
```

-------------------------------------------------------

Here is the pipeline I used to generate the data file. I write some info in the README.txt.
[dmvr_example.tar.gz](https://github.com/google-research/google-research/files/7769292/dmvr_example.tar.gz)

I cannot identify whether I miss used the dmvr, or I miss code the vatt data reader.

What should I do?

Thanks

**Comment by hassanhub** [comment]
This is a DMVR-specific issue and requires a correct understanding of their pipeline.
Please create a new issue with `[VATT] Construct and load datasets using DMVR` as the title and I'd try to address the issues as much as possible.

**Comment by Adam-fei** [comment]
Thx, I've created a new issue at [issues925](https://github.com/google-research/google-research/issues/925).

And I'll close this resolved issue. :)
