### ISSUE TITLE
Cifar10-100 Federated Split do not match original datasets

### ISSUE THREAD

**Issue by marcociccone** [google-research/google-research#924]
Hi!
I tried using the CIfar split released in [the repo](https://github.com/google-research/google-research/tree/master/federated_vision_datasets) from [this paper](https://arxiv.org/abs/2003.08082), but the `image_id` does not match the index from the original dataset downloaded from the Cifar website.

@hang-qi do you know how to recover the images from the original dataset using your split?

**Comment by 240400968** [comment]
您好，我是刘玉，我已收到您的邮件！谢谢！

**Comment by hang-qi** [comment]
@marcociccone Thanks for surfacing this issue! I have got a fix, will push an update to the affected CIFAR files soon.
