### ISSUE TITLE
tft volatility expt: Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

### ISSUE THREAD

**Issue by dhsusf** [google-research/google-research#933]
When running:

python3 '/content/drive/MyDrive/tft/script_train_fixed_params.py' $EXPT volatility $OUTPUT_FOLDER '/content/drive/MyDrive/tft/vol' $USE_GPU yes

I get: 

Computing best validation loss
7635/7635 [==============================] - 11s 1ms/sample - loss: 0.9657
Computing test loss
Traceback (most recent call last):
  File "/content/drive/MyDrive/tft/script_train_fixed_params.py", line 238, in <module>
    use_testing_mode=True)  # Change to false to use original default params
  File "/content/drive/MyDrive/tft/script_train_fixed_params.py", line 155, in main
    targets = data_formatter.format_predictions(output_map["targets"])
  File "/content/drive/MyDrive/tft/data_formatters/volatility.py", line 183, in format_predictions
    output[col] = self._target_scaler.inverse_transform(predictions[col])
  File "/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py", line 1022, in inverse_transform
    force_all_finite="allow-nan",
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 765, in check_array
    "if it contains a single sample.".format(array)
ValueError: Expected 2D array, got 1D array instead:
array=[-1.43120418  1.58885804  0.28558148 ... -1.50945972 -0.16713021
 -0.57365613].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by bartmch** [comment]
`sklearn.preprocessing.StandardScaler()` is fitted on `df[[target_column]].values` which has shape `(3488949, 1)`.
When using the inverse transform of the fitted standardscaler `predictions[col]` is a pandas series and has shape `(139635,)`.
So changing the original `self._target_scaler.inverse_transform(predictions[col])` to `self._target_scaler.inverse_transform(predictions[col].values.reshape(-1,1))` solves the issue!

**Comment by dhsusf** [comment]
Thanks for the solution. I had pretty much given up. I'm definitely interested in TFT, but it doesn't seem incredibly popular in terms of getting support.
