### ISSUE TITLE
[Hitnet] Right Disparity Image

### ISSUE THREAD

**Issue by ShivamThukral** [google-research/google-research#942]
Thanks for your amazing work. I was trying to generate the right disparity image from the given demo files. The code throws an error 
KeyError: "The name 'graph/secondary_output_disparity:0' refers to a Tensor which does not exist. The operation, 'graph/secondary_output_disparity', does not exist in the graph."
To double-check, I printed the names of all the tensors in the graph and was not able to find a key that matches the word "secondary". 
Can you please let me know how I can get the right disparity image?
Thanks in advance.

**Comment by vtankovich** [comment]
If the model does not have the field, it is not possible to predict right disparity image. The sceneflow models may have it available. You may try a simple image flipping trick: Swap left and right images and mirror them along vertical access before feeding into the network. the prediction should have an inverse operation.

**Comment by ShivamThukral** [comment]
Thanks for the reply. I will try that.
