### ISSUE TITLE
ask for llff360 config

### ISSUE THREAD

**Issue by Realitian** [google-research/google-research#948]
Hi @hedpeter ,

Thank your sharing of release code.
Btw can you share the llff config for 360 scene?
I tried to use your shared llff config for 360 captured scene, and it didn't work.

**Comment by hedpeter** [comment]
I just pushed a commit with the 360 scene config and some bug fixes. Hope
that helps!

**Comment by Realitian** [comment]
Thank you a lot of, it worked for me.
