### ISSUE TITLE
Customize kws_streaming for single wake word detection

### ISSUE THREAD

**Issue by braveheartwithlove** [google-research/google-research#967]
Hello, @rybakov, I am trying to do some modifications on your colab examples to test on a single wake word detection. 
I changed flags.wanted_words='stop' as an example, but it fails while training. Do you know what else should I change to customize it for a single wake word? Thanks!
==================================================================================================
Total params: 70,139
Trainable params: 68,603
Non-trainable params: 1,536
__________________________________________________________________________________________________
INFO:absl:Training from step: 1 
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_35504/211339909.py in <module>
      1 # Model training
----> 2 train.train(flags)

~\Desktop\google-research\kws_streaming\train\train.py in train(flags)
    163 
    164     tf.keras.backend.set_value(model.optimizer.lr, learning_rate_value)
--> 165     result = model.train_on_batch(train_fingerprints, train_ground_truth)
    166 
    167     summary = tf.Summary(value=[

C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training_v1.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1074       self._update_sample_weight_modes(sample_weights=sample_weights)
   1075       self._make_train_function()
-> 1076       outputs = self.train_function(ins)  # pylint: disable=not-callable
   1077 
   1078     if reset_metrics:

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend.py in __call__(self, inputs)
   4184       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   4185 
-> 4186     fetched = self._callable_fn(*array_vals,
   4187                                 run_metadata=self.run_metadata)
   4188     self._call_fetch_callbacks(fetched[-len(self._fetches):])

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in __call__(self, *args, **kwargs)
   1481       try:
   1482         run_metadata_ptr = tf_session.TF_NewBuffer() if run_metadata else None
-> 1483         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1484                                                self._handle, args,
   1485                                                run_metadata_ptr)

InvalidArgumentError: var and m do not have the same shape[12] [3]
	 [[{{node training/Adam/Adam/update_dense/bias/ResourceApplyAdam}}]]

**Comment by rybakov** [comment]
It looks like you set wanted_words in wrong place. 
You should set
```
FLAGS.wanted_words='stop' 
```
before 
```
flags = model_flags.update_flags(FLAGS)
```
update_flags will parse FLAGS and use wanted_words to compute "label_count" (silence and unknown labels will be added)

**Comment by braveheartwithlove** [comment]
@rybakov Actually that is what I did. 
![single](https://user-images.githubusercontent.com/17091333/152414382-e23bdf37-c481-43af-a4cd-be089823540e.png)

I also updated the model_params.py.
  def __init__(self):
    # default parameters
    self.data_url = ''
    self.train_dir = ''
    self.wanted_words = 'stop'

**Comment by braveheartwithlove** [comment]
@rybakov 
You may see the model summary looks right with 3 classes output. I am wondering where it still stores the classes as 12.

 flatten (Flatten)              (1, 128)             0           ['stream_6[0][0]']               
                                                                                                  
 dense (Dense)                  (1, 3)               387         ['flatten[0][0]']                
                                                                                                  
==================================================================================================
Total params: 70,139
Trainable params: 68,603
Non-trainable params: 1,536


InvalidArgumentError: var and m do not have the same shape[12] [3]
	 [[{{node training/Adam/Adam/update_dense/bias/ResourceApplyAdam}}]]

**Comment by rybakov** [comment]
Please delete the folder with your model and re-run colab again. I would suggest to use command [line](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_12_labels.md#ds_tc_resnet---based-on-matchboxnet), it will complain if model folder already has a model.

**Comment by rybakov** [comment]
It looks like it is restoring model from previous run, which was probably trained with 12 labels, so cleaning folder should help.

**Comment by braveheartwithlove** [comment]
Thanks @rybakov! This helps solve this problem.
