### ISSUE TITLE
flags.desired_samples = 6400

### ISSUE THREAD

**Issue by braveheartwithlove** [google-research/google-research#968]
@rybakov 
What is the reason we set desired_samples as 6400 here?  Should we change this to 16000 (1 sec of audio)?
If I run the example code of 02_inference.ipynb, it will generate an error here.

ValueError: index can't contain negative values

# pad input audio with zeros, so that audio len = flags.desired_samples
padded_wav = np.pad(wav_data, (0, flags.desired_samples-len(wav_data)), 'constant')

input_data = np.expand_dims(padded_wav, 0)
input_data.shape

**Comment by rybakov** [comment]
Training colab uses toy settings (FLAGS.clip_duration_ms = 400), please set FLAGS.clip_duration_ms = 1000 and re-train your model.

**Comment by braveheartwithlove** [comment]
Thanks @rybakov!

**Comment by rybakov** [comment]
Thank you for reporting it! I will update colabs today.
