### ISSUE TITLE
visualize training and validation loss curve for kws_streaming

### ISSUE THREAD

**Issue by braveheartwithlove** [google-research/google-research#983]
@rybakov  I finished training a model using kws_streaming colab script.  The log file is like this: fname="C:\\Users\\xxxxx\\Desktop\\google-research\\kws_streaming\\models\\ds_tc_resnet\\logs\\train\\events.out.tfevents.1644273734.NA51000227".
When I tried to use visualize_training_validation_loss.ipynb to plot the curves, it shows some errors, and I found out that the log file can not be loaded correctly ("stop parsing C:\Users\xxxxx\Desktop\google-research\kws_streaming\models\ds_tc_resnet\logs\train\events.out.tfevents.1644273734.NA51000227"). I am in Windows machine. Do you know the reason for this?
Thanks!

**Comment by braveheartwithlove** [comment]
NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\xxxxx\Desktop\google-research\kws_streaming\models\ds_tc_resnet\logs\train\events.out.tfevents.1644273734.NA51000227 : The system cannot find the path specified.
; No such process

But the log file is actually there.

**Comment by rybakov** [comment]
@braveheartwithlove  it was tested on Ubuntu and it works ok. It looks like on Winbdows it generates log files with different extensions.
Please rename all log files with the new extension ".gtc" (something like events_out_tfevents.gtc).
In the notebook you should specify path the model folder, for example model_path1 = "/tmp/ds_tc_resnet/"
Then notebook will append "logs/train/" and look for files with ".gtc" extension, the same with "logs/validation/".
The code for all above is included in the notebook, so please feel free to modify it for your needs.

**Comment by braveheartwithlove** [comment]
@rybakov I renamed the log file as you suggested. The file is clearly there.
fname="C:\\Users\\xxxxx\\Desktop\\google-research\\kws_streaming\\models\\ds_tc_resnet\\logs\\train\\events_out_tfevents.gtc"
I tried this directly:
tf.train.summary_iterator(fname)
It will show the same error as above:
NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\xxxxx\Desktop\google-research\kws_streaming\models\ds_tc_resnet\logs\train\events_out_tfevents.gtc : The system cannot find the path specified.
; No such process

**Comment by rybakov** [comment]
@braveheartwithlove I guess it is dues to
```
model_path + "logs/train/"
```
It should use os.path.join instead, for compatibility with Windows.
I would try os.path.join, or just plug full file path directly into read_log, as shown below:
```
acc_train1 = read_log(fname_train, tag="accuracy")
acc_val1 = read_log(fname_validation, tag="accuracy")
```

**Comment by braveheartwithlove** [comment]
Thanks @rybakov!
