### ISSUE TITLE
[ALBERT] Pretrainiing from scratch on multi gpu

### ISSUE THREAD

**Issue by hairzooc** [google-research/google-research#99]
Hi,
Thank you for sharing the ALBERT code :)
Would it be possible for me to run pretraining from scratch on multi gpu?
Let me know if you have any plans to implement or the ways to do that.

**Comment by kamalkraj** [comment]
Hi @hairzooc,
I have implemented a multi GPU version with TF 2.0. The classification pipeline is completed.
SQuAD WIP 
https://github.com/kamalkraj/ALBERT-TF2.0

**Comment by brightmart** [comment]
If i am not wrong, pretrain on gpu for albert is time consuming and need lots of work before it can wot. But you can train it on TPU with existing codes and run 10 times faster or more than GPU.

**Comment by hairzooc** [comment]
Thanks for your reply.
I know that TPU could be great choice but I have 8 x Titan RTX 24GB.
So I just wanted to check if it's possible to run on multi GPU.
